### ISSUE TITLE
Replace `arePointsEqual` with `_.isEqual`

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-play#101]
For #84 

Consider replacing this bit of code in Subitizer.js:

```ts
  /**
   * Compares two sets of points and returns if they are equal or not.
   */
  private static arePointsEqual( pointsSetOne: Vector2[], pointsSetTwo: Vector2[] ): boolean {
    let pointsAreEqual = true;
    if ( pointsSetOne.length === pointsSetTwo.length ) {
      for ( let i = 0; i < pointsSetOne.length; i++ ) {
        if ( !pointsSetOne[ i ].equals( pointsSetTwo[ i ] ) ) {
          return false;
        }
      }
    }
    else {
      pointsAreEqual = false;
    }
    return pointsAreEqual;
  }
```

... with:

```ts
_.isEqual( pointsSetOne, pointsSetTwo )
```

To convince yourself that they are equivalent, put this line before the second `return` statement in `arePointsEqual`, and test with `?ea&fuzz`:

```ts
assert && assert( pointsAreEqual === _.isEqual( pointsSetOne, pointsSetTwo ) );
```

Documentation for `_.isEqual`: https://lodash.com/docs/#isEqual

**Comment by Luisav1** [comment]
Fixed in the commit above, back to @chrisklus to review and close if all looks good.

**Comment by chrisklus** [comment]
Commit looks good. I forgot that `_.isEqual` would know how to drill down and compare `v.x` and `v.y`, nice. Closing.
