### ISSUE TITLE
Unnecessary overrides of NumberPlayGameLevelNode reset in subclasses

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-play#102]
For #84 

In CountingGameLevelNode.js and in SubitizeGameLevelNode.js, you're overriding `reset` for the sole reason of changing its accessibility from protected to public:

```js
  public reset(): void {
    super.reset();
  }
```

This is undesirable. Simply make `reset` public in the supertype NumberPlayGameLevelNode, then delete these overrides.

**Comment by Luisav1** [comment]
@chrisklus and I worked on this together. Closing.
