### ISSUE TITLE
Arrow functions don't need curly braces or return when the body is a single expression

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-play#103]
For #84 

For arrow function like this one in SubitizeLoadingBarNode.js:

```js
    this.loadingBarWidthProperty.link( loadingBarWidth => {
      loadingBarRectangle.setRectWidth( loadingBarWidth );
    } );
```

The curly braces (and `return`, if there was one) are unnecessary when the body of the function is a single expression.  For example, the above can be written:

```js
    this.loadingBarWidthProperty.link( loadingBarWidth => loadingBarRectangle.setRectWidth( loadingBarWidth ) );
```

You don't necessarily have to change occurrences of this, but it's good to know.

**Comment by Luisav1** [comment]
Fixed in the commits above, back to @chrisklus to review and close if all looks good.

**Comment by chrisklus** [comment]
Commits look good and I didn't see any other cases that were appropriate to change, thanks! Closing.
