### ISSUE TITLE
branch: labScreen

### ISSUE THREAD

**Issue by chrisklus** [phetsims/number-play#104]
This branch is needed to keep some unused assets around for the Lab screen. It will be deleted once development on the Lab screen is resumed and it's added back to the sim again.

**Comment by Luisav1** [comment]
Need to revert the commit https://github.com/phetsims/number-play/commit/4140e6c091b86d5ccc5a6799cbeaeb898d360522 before working on the lab screen again.

**Comment by chrisklus** [comment]
This branch was merged into master, closing.
