### ISSUE TITLE
NumberPlayGameModel creates levels conditionally, which will break PhET-iO API.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-play#105]
For #84. I originally mentioned in https://github.com/phetsims/number-play/issues/92#issuecomment-996283330, but I thought this was worthy of its own issue, so I moved it here.

NumberPlayGameModel currently creates instances of CountingGameLevel and SubitizeGameLevel, based on the value of `?gameLevels`.   Since I see that NumberPlayGameModel  has a `tandem` parameter, Games levels will presumably be PhET-iO instrumented in the future.  And conditionally creating them will then be a big problem - omitting a level will break the PhET-iO API, and potentially the client's wrapper code.  

To resolve this, NumberPlayGameModel must ALWAYS create all 4 levels. Then the view should expose only those levels that are specified by `gameLevels`, by hiding level-selection buttons that are no included in `gameLevels`. See `equality-explore.LevelSelectionNode` and `fourier-making-waves.WaveGameLevelSelectionNode` for examples.

This change is necessary regardless of how you choose to address the `gameLevels` query parameter in  https://github.com/phetsims/number-play/issues/92.

**Comment by Luisav1** [comment]
@chrisklus and I worked on this together. We are creating all the levels and the buttons now but are only including the specified buttons in the selection. We might adjust how this is done depending on the results of the discussion from #92.

**Comment by pixelzoom** [comment]
Mentioned at 12/21 design meeting for #92...   To "PhET-iO proof" the sim, all of the buttons should be added to scenegraph, then set `visible: false` for the ones that are not in `gameLevels`.  This will allow the PhET-iO client to get at them if needed.

Your layout for the level-selection buttons will be something like:

```js
new VBox( {
  children: [
    new HBox( { children: [ ... ] }, ... ),   // row of Counting buttons
    new HBox( { children: [ ... ] }, ...),    // row of Subitize buttons
  ],
  ...
} );
```

... then confirm with @amanda-phet that the layout looks good for various values of `?gameLevels`.

**Comment by chrisklus** [comment]
This work was completed, closing.
