### ISSUE TITLE
Make new images for the linking buttons and game screen

### ISSUE THREAD

**Issue by chrisklus** [phetsims/number-play#108]
While working on #107, @Luisav1 noticed that the buttons for the grouping and linking have outdated images. We should at least update them with the new dogs, and consider revisiting their design. It might be appropriate to make them in code. 

The design of the first seems solid. The second is hard to see as is and will be hard to show the same representation of two dogs one on card since they will be so small. We're also concerned about showing a card in the button since it might give the appearance of a double border (the card itself has a defined shape and border like the button does). The third we think could use some work - I'm not a fan of the lock icon. We both think it could be nice to try a 1 card and a single dog card next to each other at the full height of the button. There could be similar busyness issues with the border of the cards and the border of the button, though.

![image](https://user-images.githubusercontent.com/5618316/148812448-1030d7e6-b9d0-4131-b05a-2eb9cf8669ae.png)

**Comment by chrisklus** [comment]
We also noticed that the Game Screen button images for the counting game should be updated now that the turtle was removed in #107

**Comment by amanda-phet** [comment]
This seems to be done. @chrisklus are you still tweaking these, or can this be closed?

**Comment by chrisklus** [comment]
@amanda-phet and I looked this and are about ready to close - @amanda-phet is going to make a version of the middle icon (dogs on the card) with a little more padding between the edges of the dog and the card they are on.

Then, we are going to close this issue and repopen a new one in the future if we want to revisit these icons when work on this sim continues in the future.

**Comment by amanda-phet** [comment]
Over to you @chrisklus to make sure it's in the sim and looks ok.

**Comment by chrisklus** [comment]
Looking great, thanks @amanda-phet! Closing.
