### ISSUE TITLE
Sound is muted and disabled

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-play#109]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/761.
The sim does not have any game sounds. The nav bar shows a sound button, which is muted by default and greyed out so sound cannot be turned on. This is the default state of the sim and no query parameters were used to achieve this state.

**Visuals**
<img width="223" alt="mute" src="https://user-images.githubusercontent.com/41024075/148834720-413db2f9-53dd-45e0-a66c-293ca3ab1d75.png">

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Number Play‬
URL: https://phet-dev.colorado.edu/html/number-play/1.0.0-dev.35/phet/number-play_all_phet.html?screens=4
Version: 1.0.0-dev.35 2022-01-10 18:25:22 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by chrisklus** [comment]
Thanks @KatieWoe! @Luisav1 and I turned on sound for the sim in the above commit. It looks like the game sounds are working as expected, with the exception of clicking a correct and incorrect button in the challenges. We opened https://github.com/phetsims/number-play/issues/115 to address that case. Those sounds aside, please verify this issue on master and close if it looks good.

**Comment by KatieWoe** [comment]
Looks good on master
