### ISSUE TITLE
Query parameter "subitizerTimeVisible" does not work

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/number-play#110]
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.01.1

**Browser**
safari

**Problem description**
For https://github.com/phetsims/qa/issues/761

I am getting an Invalid Query Parameter message when I add  'subitizerTimeVisible' to the end of the url. I also tried subitizerTimeVisible=true as did @KatieWoe and that did not work. Is there something else that needs to be added?

**Steps to reproduce**
Add &subitizerTimeVisible to the end of the url

**Visuals**
<img width="609" alt="Screen Shot 2022-01-10 at 3 46 22 PM" src="https://user-images.githubusercontent.com/87318828/148837735-8a4fc21c-a2d3-4741-9a17-c08efa4892cd.png">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Number Play‬
URL: https://phet-dev.colorado.edu/html/number-play/1.0.0-dev.35/phet/number-play_all_phet.html?screens=4&subitizerTimeVisible
Version: 1.0.0-dev.35 2022-01-10 18:25:22 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15
Language: en-US
Window: 1386x701
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by chrisklus** [comment]
Thanks @Nancy-Salpepi! The value is of type `number`, but it's clear now that this is a very misleading name for the query parameter, since just about every type that ends in `visible` at PhET is referencing a `boolean` (for query parameters, either as a flag or with values `true` and `false`).

For now, please test it with numbers and @Luisav1 and I opened https://github.com/phetsims/number-play/issues/111 to rename it.

**Comment by Nancy-Salpepi** [comment]
@chrisklus Query parameter works when I use numbers. Thanks for the clarification!
