### ISSUE TITLE
subitizerTimeVisible query parameter should be renamed

### ISSUE THREAD

**Issue by chrisklus** [phetsims/number-play#111]
From https://github.com/phetsims/number-play/issues/110.

The name `subitizerTimeVisible` is very misleading, as discovered by @Nancy-Salpepi and @KatieWoe. It looks like a boolean value, but instead is used to get a number input for how long the subitizer shape should flash for during a challenge.

@Luisav1 and I thought of a couple possibilities:

`subitizerTimeShown`
`subitizerTime`

Marking for design meeting to discuss with the team.

**Comment by chrisklus** [comment]
I forgot to bring this up in last design meeting. @amanda-phet any thoughts?

**Comment by amanda-phet** [comment]
`subitizerTimeShown` sounds good to me. Or `subitizeTimeShown`.

**Comment by chrisklus** [comment]
Sounds good, thanks. I went with `subitizeTimeShown`. "subitizer" seems like an internal name that @Luisav1 and I invented for the type that drives the subitize game model :) Closing.
