### ISSUE TITLE
Subitize level title

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-play#114]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/761
I'm wondering about calling the subitize levels subitize? I had to look the term up to know what it meant. I doubt a kid would know what it meant. I know that the students won't be relying on words for the sim, but it did strike me as odd.

**Visuals**
<img width="212" alt="subable" src="https://user-images.githubusercontent.com/41024075/148853848-9ebd429b-563e-4204-8ce6-b580062f4680.png">

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Number Play‬
URL: https://phet-dev.colorado.edu/html/number-play/1.0.0-dev.35/phet/number-play_all_phet.html?screens=4
Version: 1.0.0-dev.35 2022-01-10 18:25:22 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by chrisklus** [comment]
Thanks @KatieWoe! From our discussion on Slack:

>I think that’s okay - we talked about it a little in design and @Luisav1 and I just rediscussed - we basically eliminated all words from the game interaction since we’re not counting on the target age group to be able to read. So the level titles are a bit of a formality, maybe for teachers? The kids are just intended to recognize them by the color and icon. Not sure why we still have the choose your game string too then. I dunno, might be worth opening an issue to share your concern with @amanda-phet to get her thinking about it again?

Assigning to @amanda-phet - we may have discussed this already to feel free to close if all set.

**Comment by amanda-phet** [comment]
That's correct that it's for the teacher. However, this reminds me that we need an info button on the level selection screen. Can we do something like this? 

![image](https://user-images.githubusercontent.com/7852916/149049095-6ce4bc26-05f9-483f-990e-6cded7298cd9.png)

![image](https://user-images.githubusercontent.com/7852916/149049711-9c6a4a9b-c85b-4353-81ae-781f97a84df7.png)


See Equality Explorer for a recent example of this. https://phet.colorado.edu/sims/html/equality-explorer/latest/equality-explorer_en.html 

Make a Ten also has this, but the button has the older icon.

**Comment by chrisklus** [comment]
Sure thing @amanda-phet. The dialog screenshot made @Luisav1 and I think that the game names should either be "Counting" and "Subitizing" or "Count" and "Subitize", what do you think?

**Comment by amanda-phet** [comment]
Ha, I was thinking the same thing. Let's call the second game "Subitizing."

**Comment by chrisklus** [comment]
In the above commits I reformatted the info dialog to remain correctly aligned for any length strings, closing.
