### ISSUE TITLE
Play areas can get out of sync with the total

### ISSUE THREAD

**Issue by chrisklus** [phetsims/number-play#124]
This has been around for a long time, I just hadn't made an issue for it yet. I was looking into it tonight and have figured out what's going on.

The issue is caused when a paper number is created from the creator node, animates out into the play area, but is still touching the creator node when it stops animating. This shouldn't happen in general, but the underlying bug here is that when the number then goes back into the panel (because it's in contact with it when it stopped animating), the number is removed but its value isn't subtracted from the total. This leaves the play area with one fewer paper numbers than the total per instance of the bug. In this issue, I'll fix what I just described as the underlying bug, as well as adjust where the numbers are allowed to animate out to.

**Comment by chrisklus** [comment]
Both issues were fixed in the above commits. I also found another bug related to grouping/linking that I fixed. There is more to discuss for this issue - I will update it with details soon.

**Comment by chrisklus** [comment]
>There is more to discuss for this issue

For QA: The one bug I know of for sure right now regarding this issue is that the play areas can get out of sync if you "organize" the play objects while any are on their way back to the creator panel.

**Comment by chrisklus** [comment]
Another thing to note - I don't think this issue will hold up well for multi-touch yet - if it is clearly easy to mess up, please just make a note in https://github.com/phetsims/number-play/issues/6. Thanks!

**Comment by chrisklus** [comment]
>For QA: The one bug I know of for sure right now regarding this issue is that the play areas can get out of sync if you "organize" the play objects while any are on their way back to the creator panel.

This should be fixed now.

**Comment by Nancy-Salpepi** [comment]
I wasn't able to reproduce either of the situations described. Looks fixed!

**Comment by chrisklus** [comment]
That is great news, thanks @Nancy-Salpepi!
