### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-play#127]
For https://github.com/phetsims/qa/issues/771. This seems to indicate a memory leak.
Start: 25.4 MB
1 min: 127
2 min: 200
3 min: 250
4 min: 297
5 min: 343

**Comment by KatieWoe** [comment]
This looks similar in dev.45
<img width="352" alt="newmem" src="https://user-images.githubusercontent.com/41024075/151854202-738521be-72ae-4795-a07b-30f6dfe60a41.png">

**Comment by chrisklus** [comment]
Oops, I forgot to update this issue on Friday. @jonathanolson helped me look into the memory status of this sim and we found that it had been greatly improved since the last tests. Initial size was around 50 MB and after 5-7 min of testing we never saw it go above 56 MB. 

There was one dragListener to dispose that I am about to commit. I will do a new memory test on 1.0 prototype to confirm no maintenance release is needed for this issue

**Comment by marlitas** [comment]
Did a memory test on each individual screen today and got this:

Screen 1:
![Screenshot 2023-01-05 at 1 10 15 PM](https://user-images.githubusercontent.com/42476338/210896181-3ef7e08f-efba-4643-a146-ff8b8e8ff5b5.png)

Screen 2:
![Screenshot 2023-01-05 at 1 24 39 PM](https://user-images.githubusercontent.com/42476338/210896198-aaa013e4-49f1-44a7-a438-7279453a5146.png)

Screen 3:
![Screenshot 2023-01-05 at 1 30 09 PM](https://user-images.githubusercontent.com/42476338/210896220-fa0dc5ad-ca1e-48f8-93ed-69becf96e6f2.png)

Screen 4:
![Screenshot 2023-01-05 at 1 33 25 PM](https://user-images.githubusercontent.com/42476338/210896246-9cf87294-f51c-406b-9ee2-d70c263d0e0d.png)

It's pretty apparent that Screen 4 has a memory leak. Going to address that first, and then test again.

**Comment by marlitas** [comment]
@zepumph and I addressed the leaky code in the Lab Screen. Another full sim memory test indicates there are no other leaks. Assign to @chrisklus for review.
<img width="187" alt="Screenshot 2023-01-10 at 11 52 06 AM" src="https://user-images.githubusercontent.com/42476338/211636998-0ac2f6e5-9355-40d2-b282-c50b93897cf4.png">

**Comment by chrisklus** [comment]
@marlitas and I co-reviewed and everything looks great, thanks! Closing.
