### ISSUE TITLE
Cannot read properties of undefined reading x

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-play#128]
For https://github.com/phetsims/qa/issues/771. While fuzzing for https://github.com/phetsims/number-play/issues/127 this error appeared in the console 3 times in the 5 minutes of the test. The fuzzing did not stop due to the errors.
<img width="350" alt="bug" src="https://user-images.githubusercontent.com/41024075/151633937-87ff2549-c4b2-4a5b-bb71-c18aaf16daa7.png">

**Comment by KatieWoe** [comment]
I fuzzed for around 10 minutes on dev.45 and this didn't show up.

**Comment by chrisklus** [comment]
Thanks @KatieWoe!

>I fuzzed for around 10 minutes on dev.45 and this didn't show up.

Good to know - I haven't seen it on CT recently either. Closing.
