### ISSUE TITLE
Update colors

### ISSUE THREAD

**Issue by chrisklus** [phetsims/number-play#129]
In 1/27 design meeting, @ariel-phet mentioned he wasn't loving the darker green accordion boxes, primarily because their color clashes with the green plus when they are closed. I expressed I've also not been loving the greens in general, and would like to try out some other options.

**Comment by chrisklus** [comment]
Oops, I accidentally duplicated this issue over in https://github.com/phetsims/number-play/issues/122, closing.

**Comment by chrisklus** [comment]
Here's a few different directions we could play with if we like any of them.

Reference: https://phet-dev.colorado.edu/html/number-play/1.0.0-dev.40/phet/number-play_en_phet.html
Purple: https://phet-dev.colorado.edu/html/number-play/1.0.0-dev.41/phet/number-play_en_phet.html
Slightly darker purple: https://phet-dev.colorado.edu/html/number-play/1.0.0-dev.44/phet/number-play_en_phet.html
Brown: https://phet-dev.colorado.edu/html/number-play/1.0.0-dev.42/phet/number-play_en_phet.html
Blue: https://phet-dev.colorado.edu/html/number-play/1.0.0-dev.43/phet/number-play_en_phet.html

Reminder that the compare screen is very impacted by these changes too.

**Comment by kathy-phet** [comment]
@chrisklus - Thanks for seeding a color discussion. I want to understand the connection to the compare screen. I see that the background to the Ten and Twenty screens become the backgrounds on the compare screen ... but I don't really see a reason that has to be the case. These could have their own colors. I don't recall a pedagogical reason they were tied together.

**Comment by ariel-phet** [comment]
@chrisklus I think dev.43 or dev.41 are my favorites, with a slight preferences for dev.43 -- I think that does not overemphasize the top panels and also looks very clean.

**Comment by chrisklus** [comment]
>I see that the background to the Ten and Twenty screens become the backgrounds on the compare screen ... but I don't really see a reason that has to be the case. These could have their own colors. I don't recall a pedagogical reason they were tied together.

Good question - I'm not sure of a pedagogical reason. I think that was @amanda-phet's design choice and I like it. I didn't use the exact same color for the background of the ten screen and the left accordion box on the compare screen for any of those colors, though they are all very close. I found it more natural to use a slightly lighter shade as the screen background and slightly darker as the accordion box background. The ten screen background and the twenty screen Total accordion box background are the same, though.

Thanks for you feedback @ariel-phet. Those are my preferences as well, though I think I slightly prefer dev.41 because it feels the most balanced on the ten screen and i just like purple in general.

**Comment by amanda-phet** [comment]
I like dev.41 the best. I may provided a slightly different shade of purple for the accordion boxes, but if it was the same as dev.41 now I'd be happy with that. 

The backgrounds on the compare screen are just to reuse colors. There is no pedagogical reason for them having those colors, just using the light background colors from the previous screens looked nice. I like the purple and orange myself. Would you prefer something else @kathy-phet ?

**Comment by chrisklus** [comment]
We are happy with the new color set, closing.
