### ISSUE TITLE
For loop cannot loop

### ISSUE THREAD

**Issue by samreid** [phetsims/number-play#13]
As part of https://github.com/phetsims/chipper/issues/814, ESLint detected this code in number-play/js/common/view/OnesPlayAreaNode.js

```js
    for ( let i = 0; i < droppedNodes.length; i++ ) {
      const droppedNode = droppedNodes[ i ];
      const droppedPaperNumber = droppedNode.paperNumber;

      // allow any two numbers to be combined
      this.playArea.collapseNumberModels( this.availableViewBoundsProperty.value, draggedPaperNumber, droppedPaperNumber );
      return; // No need to re-layer or try combining with others
    }
```

Note that the loop cannot loop since it always returns.  This seems potentially buggy, so I'll mark blocks publication.  I will also opt out of the lint rule for now so that it doesn't show as a lint error, but as part of the resolution for this issues the eslint disable directive should be removed.  Assigning to responsible dev.

**Comment by chrisklus** [comment]
Thanks @samreid! I'll investigate when starting to work on this sim again. Added to my TODO list in the dev epic, https://github.com/phetsims/number-play/issues/11

**Comment by chrisklus** [comment]
This code block was removed when fixing another bug (ha!). I found that commit and tagged it above to this issue. Closing.
