### ISSUE TITLE
Should sound be interrupted when sim is muted?

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-play#132]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/771.
If you have the sim read something out, then mute the sim in the nav bar while it is reading, the sentence finishes. The sim is then muted and no new sounds start, but should already occurring sounds also stop?

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Number Play‬
URL: https://phet-dev.colorado.edu/html/number-play/1.0.0-dev.45/phet/number-play_all_phet.html?screens=1,2,3
Version: 1.0.0-dev.45 2022-01-31 11:53:19 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by chrisklus** [comment]
Assuming this is not hard, I'll add a listener to the sound property to cancel the current voice. Thanks @KatieWoe !

**Comment by jessegreenberg** [comment]
As mentioned in https://github.com/phetsims/number-play/issues/144#issuecomment-1032048385, I think this should be fixed with that issue, @chrisklus can you confirm?

**Comment by chrisklus** [comment]
Confirmed that this was fixed in https://github.com/phetsims/number-play/issues/144, thanks! Closing.
