### ISSUE TITLE
Object type in Compare screen doesn't reset with reset all

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-play#133]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/771.
On the compare screen, they type of object in the play area does not reset with the reset all button. When you first get to the screen both boxes use the puppy object. But if you switch to apples or numbers, they stay apples or numbers. This does not seem to happen on the other screens.
**Steps to reproduce**
1. Go to the compare screen
2. Switch object types to apples or numbers
3. Hit reset all

**Visuals**
![comparereset](https://user-images.githubusercontent.com/41024075/151879278-94aeee92-920f-4dbc-bb75-a0205c881239.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Number Play‬
URL: https://phet-dev.colorado.edu/html/number-play/1.0.0-dev.45/phet/number-play_all_phet.html?screens=1,2,3
Version: 1.0.0-dev.45 2022-01-31 11:53:19 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by chrisklus** [comment]
Thanks @KatieWoe! I fixed this while working on https://github.com/phetsims/counting-common/issues/5. Back you to confirm on phettest, feel free to close if all set.

**Comment by KatieWoe** [comment]
Looks good on master
