### ISSUE TITLE
Touch areas overlap 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/number-play#135]
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.0.1

**Browser**
Safari

**Problem description**
For https://github.com/phetsims/qa/issues/771

The touch areas for the bottom number spinner/object in each play area overlap. This is seen on the first 3 screens. 

**Visuals**
<img width="673" alt="Screen Shot 2022-02-01 at 12 33 16 PM" src="https://user-images.githubusercontent.com/87318828/152021626-492524be-393e-4f02-92f7-5de9d6669493.png">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Number Play‬
URL: https://phet-dev.colorado.edu/html/number-play/1.0.0-dev.45/phet/number-play_all_phet.html?screens=1,2,3&secondLocale=es
Version: 1.0.0-dev.45 2022-01-31 11:53:19 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15
Language: en-US
Window: 1409x687
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Nancy-Salpepi** [comment]
Also, the touch areas for the objects are inconsistent for scenes 2 and 3.
Cards:
<img width="146" alt="Screen Shot 2022-02-01 at 12 46 51 PM" src="https://user-images.githubusercontent.com/87318828/152022733-c3b9f52e-7adc-436a-ae1e-03ce8f5ea5bc.png">



Locked:
<img width="146" alt="Screen Shot 2022-02-01 at 12 46 13 PM" src="https://user-images.githubusercontent.com/87318828/152022572-eab15d2a-3705-441e-88f8-71fe5fb0aa24.png">

**Comment by chrisklus** [comment]
@kathy-phet recommended putting the arrow buttons on top - I'll take a look and see I that would be best or trimming the left side.

**Comment by chrisklus** [comment]
Fixed in the above commits, here is the result:

<img width="1402" alt="image" src="https://user-images.githubusercontent.com/5618316/163415009-bd9b3b1b-073a-40ba-bc0c-31cd504be240.png">

<img width="1411" alt="image" src="https://user-images.githubusercontent.com/5618316/163415085-19b6d63f-b3c9-4101-b698-3ac8a1a8765b.png">


Thanks @Nancy-Salpepi! Closing.
