### ISSUE TITLE
Replace usages of voicingManager with a different instance of SpeechSynthesisAnnouncer

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/number-play#144]
From https://github.com/phetsims/utterance-queue/issues/34, the usage of voicingManager that was introduced for https://github.com/phetsims/number-play/issues/136 should be replaced with a new instance of a SpeechSynthesisAnnouncer. In https://github.com/phetsims/utterance-queue/issues/34 voicingManager now extends a base class that supports SpeechSynthesis called SpeechSynthesisAnnouncer so this should be possible now.

**Comment by jessegreenberg** [comment]
Over slack @chrisklus mentioned there was a voicing feature bleeding over from our temporary usage of voicingManager.enabledProperty.value = true. When muting the sim we would hear "Sim voicing off". Using a different Announcer with a different enabledProperty should fix that.

**Comment by jessegreenberg** [comment]
There are no more usages of voicingManager in number-play. @chrisklus can you please review the changes and the behavior? In particular I wanted to point out
- In https://github.com/phetsims/number-play/commit/5881df036da7b1bf3392475e3bc7c287007f60e1 I removed the audioManager.audioEnabledProperty check, it shouldn't be necessary anymore. Can you verify this is OK?
- The issue in https://github.com/phetsims/number-play/issues/144#issuecomment-1032000693 should be fixed, can you verify?
- I think https://github.com/phetsims/number-play/issues/132 should be fixed with this as well, can you confirm?
- Does the initialization of `numberPlaySpeechSynthesisAnnouncer` look OK to you, and correct to do as long as speech synthesis is supported?
- A few places where `voicingManager.initialized` was checked were replaced with `SpeechSynthesisAnnouncer.isSpeechSynthesisSupported`.

**Comment by chrisklus** [comment]
Thanks @jessegreenberg!

>In https://github.com/phetsims/number-play/commit/5881df036da7b1bf3392475e3bc7c287007f60e1 I removed the audioManager.audioEnabledProperty check, it shouldn't be necessary anymore. Can you verify this is OK?

Awesome, it's working great for me.

>The issue in https://github.com/phetsims/number-play/issues/144#issuecomment-1032000693 should be fixed, can you verify?

Yep, fixed on my end.

> I think https://github.com/phetsims/number-play/issues/132 should be fixed with this as well, can you confirm?

Yes indeed, nice!

> Does the initialization of `numberPlaySpeechSynthesisAnnouncer` look OK to you, and correct to do as long as speech synthesis is supported?

Yes, that looks great.

>A few places where `voicingManager.initialized` was checked were replaced with `SpeechSynthesisAnnouncer.isSpeechSynthesisSupported`.

`SpeechSynthesisAnnouncer.isSpeechSynthesisSupported` seems really good for guarding `numberPlaySpeechSynthesisAnnouncer.initialize`. Do you think the other places (like when creating a SpeechSynthesisButton) would make sense to check `numberPlaySpeechSynthesisAnnouncer.initialized`?

Everything is looking great, I appreciate all your work for supporting this case! I'll assign back to you for the one question above, feel free to close if nothing left to do, otherwise please assign to me to proceed with your recommendation.

**Comment by jessegreenberg** [comment]
> Do you think the other places (like when creating a SpeechSynthesisButton) would make sense to check numberPlaySpeechSynthesisAnnouncer.initialized

Sorry it took so long, but sure! I don't feel too strongly, but could see that being cleaner if you prefer to check `initialized`.

**Comment by chrisklus** [comment]
@jessegreenberg great, thanks. I went ahead and swapped them. I think we're all set here, thanks @jessegreenberg! Closing.
