### ISSUE TITLE
Should the compare screen controls be swapped?

### ISSUE THREAD

**Issue by chrisklus** [phetsims/number-play#145]
I would like to consider swapping the placement of the scene buttons + checkbox with the locale switch + speech button. This would keep the speech button and locale switch consistent on all screens. This seems extra nice for when alternative input is added to this sim. The only drawback i see to this change is that the checkbox will be aligned by its text on the right instead of the nice edge of the checkbox on the left.

**Comment by chrisklus** [comment]
Completed in the above commit - I like it, want to take a look @amanda-phet?

**Comment by amanda-phet** [comment]
Looks good to me!
