### ISSUE TITLE
Create a "base" for the compare stacks

### ISSUE THREAD

**Issue by chrisklus** [phetsims/number-play#146]
We mentioned doing this a long time ago - having some indicator at the bottom of the stacks of squares so that zero doesn't match the no selection option.

**Comment by amanda-phet** [comment]
Discussed 2/10/22 meeting and would like to defer this for now, but is probably something worth considering in the future. 

If we want something for right now, we can try a thin black line under the stacks.

**Comment by chrisklus** [comment]
I tried out a simple line, want to take a look @amanda-phet?

**Comment by amanda-phet** [comment]
Did you try anything lighter weight, such as the same weight that we use around the accordion boxes?

**Comment by chrisklus** [comment]
@amanda-phet and I met to discuss and decided on making it a bit thinner. We are ready to close!
