### ISSUE TITLE
Query parameter for hiding accordion boxes

### ISSUE THREAD

**Issue by chrisklus** [phetsims/number-play#150]
At design meeting today, @kathy-phet brought a up teacher suggestion that we may want to implement for final publication. It's a query parameter to specify accordion boxes that should be hidden. We thought it could look like `hideRepresentations=1,3` or `hideRepresentations=word,tenFrame` if someone wanted to hide the Word and Ten Frame accordion box, for example.

**Comment by amanda-phet** [comment]
We aren't doing any new features for this sim, but if users request this feature we could return to this discussion.
