### ISSUE TITLE
Language toggle should probably not be in accordion box

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-play#151]
IW brought up that the accordion box on the Ten and Twenty screens should probably not be hidden in an accordion box. 

This is going to require some design discussions because I am not seeing an obvious way to redesign those two screens.

**Comment by amanda-phet** [comment]
Discussed options 3/17/22 in design meeting. Would like to see how these two options look: 

1. Shorten the height of the "word" accordion box and leave the toggle in a static location between the word and ones accordion boxes
2. Shorten the height of the "word" accordion box and put he toggle just below it whether expanded or collapsed (so the control moves depending on the state of the accordion box) 
3. Keep the accordion box the current size and hack the toggle to be outside the accordion box when collapsed, and inside the accordion box when expanded, in a static location

@chrisklus will make three versions of the sim so we can compare all options!

**Comment by chrisklus** [comment]
Tried these out and made three dev versions:

1. https://phet-dev.colorado.edu/html/number-play/1.0.0-dev.49/phet/number-play_all_phet.html?secondLocale=es
2. https://phet-dev.colorado.edu/html/number-play/1.0.0-dev.50/phet/number-play_all_phet.html?secondLocale=es
3. https://phet-dev.colorado.edu/html/number-play/1.0.0-dev.48/phet/number-play_all_phet.html?secondLocale=es

I suppose 2 is my preference, but I'm not loving any of them. For 1 and 2, it's a little weird that the switch is vertically centered relative to the bottom of the Total accordion box, but i had to bring it that low to leave enough vertical space in the Twenty Word accordion box. In general, looks okay not great to me. And in 3 I think it's floating too far away from the top of the Ones accordion box when the Word accordion box is closed.

One thing I forgot to do but could is make the Word accordion box the normal height in 1 and 2 when the locale switch is not showing (like in this case https://phet-dev.colorado.edu/html/number-play/1.0.0-dev.49/phet/number-play_all_phet.html).

Assigning to @amanda-phet for review.

**Comment by amanda-phet** [comment]
On 3/29/22 @kathy-phet shared the following: 

>I asked Ian about this this morning when I was meeting with him. 
>He noted that in the latest version, when you toggle the control nothing visual changes so its hard to know its working. 
>I don't know what the implications would be for toggling the entire translation words of the sim, but I'm curious if its easy or not? Amanda, what are your thoughts on pros/cons here? 

I think a global control like this would make more sense to be in the navbar, since that is persistent, and we haven't done anything like that before. 

Ian first suggested we move the toggle out of the accordion box, so in this case, I would ask which is better in his opinion- see nothing change, or hide it in the accordion box. I personally didn't have a huge issue with it being in the accordion box, but it sounded like it was a really important control to access without having to expand the box.

**Comment by amanda-phet** [comment]
Discussed 3/31/22 and we'd like to move forward with option 2. 

We would also like to move forward with the following proposal to address Ian's concern: 

The accordion box title will say Word (English) or Word (Espanol) depending on the toggle selection, but if `secondLocale` is not being used the title will just say Word.

**Comment by chrisklus** [comment]
This is ready for review. I'll add a link for viewing when available.

**Comment by chrisklus** [comment]
This seems to be working well and I sent @amanda-phet a screenshot over slack. We don't love having the language in the word accordion box title, but it's the best we can do for now. Closing.
