### ISSUE TITLE
When language toggle triggers speech is inconsistent across screens

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/number-play#157]
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.3.1

**Browser**
Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/797, when using both the ReadAloud and secondLocale= es query parameters, I noticed an inconsistency between screens. On the Compare Screen, when I toggle between the 2 locales, the statement is read aloud in the new language. If I do the same of the Ten or Twenty Screen, that does not happen. 

**Steps to reproduce**
1. add both query parameters to url: readAloud and secondLocale=es
2. On the Compare screen, toggle to Español 
3. Toggle back to English
4. Go to the Ten or Twenty screen, toggle to Español
5. Toggle back to English

**Visuals**

https://user-images.githubusercontent.com/87318828/163582164-88f6b843-1514-4bda-bd95-a206222fbd62.mov

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Number Play‬
URL: https://phet-dev.colorado.edu/html/number-play/1.0.0-rc.1/phet/number-play_all_phet.html?secondLocale=es&readAloud
Version: 1.0.0-rc.1 2022-04-14 15:43:27 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36
Language: en-US
Window: 1431x690
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by chrisklus** [comment]
Thanks @Nancy-Salpepi! Discussed with @amanda-phet and we think the Ten and Twenty screen behavior is correct. I'll change the Compare screen.

**Comment by chrisklus** [comment]
Completed above and ready for cherry-picking.

**Comment by KatieWoe** [comment]
Looks good in https://phet-dev.colorado.edu/html/number-play/1.0.0-rc.2/phet/number-play_all_phet.html?secondLocale=es&readAloud

**Comment by chrisklus** [comment]
Also cherry-picked for https://github.com/phetsims/number-play/issues/166.
