### ISSUE TITLE
Should the object card expand at 10 objects, or 11?

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-play#159]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/797.
When you make the objects cards in the sim, and combine the cards, the card expands when you add a 10th object. This leaves a large, empty white space to the right. This is especially noticeable on the Ten page, where no other objects can be add at this point. It seems like the expansion should occur at the 11th object instead. If this is intentional, feel free to close.

**Visuals**
<img width="220" alt="tenortwenty" src="https://user-images.githubusercontent.com/41024075/163593804-a382ff21-8a6e-4ef5-8692-780347ffe482.png">

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Number Play‬
URL: https://phet-dev.colorado.edu/html/number-play/1.0.0-rc.1/phet/number-play_all_phet.html
Version: 1.0.0-rc.1 2022-04-14 15:43:27 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by chrisklus** [comment]
Thanks @KatieWoe  - while it does look a little odd, this is intentional so that the size matches the ten card for the paper numbers (so the linking behavior works out nicely when dragging them), and so that single digits can be overlaid on the blank space (like paper ones over the zero of the ten). Closing.
