### ISSUE TITLE
Only English voice is heard 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/number-play#160]
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.3.1

**Browser**
Safari

**Problem description**
For https://github.com/phetsims/qa/issues/797 

Using the query parameter secondLocale=es, I am only hearing the English speaking voice. When I switch to Español, it is the English voice saying the Spanish word. It is almost the opposite of what I originally reported in https://github.com/phetsims/number-play/issues/134.
 
**Steps to reproduce**
1. add the query parameter secondLocale=es
2. Go to any screen and press the megaphone button to hear English
3. Toggle to Español and then press the megaphone button

**Visuals**
Sorry for the birds chirping in this video!

https://user-images.githubusercontent.com/87318828/163607745-f61a1499-510b-4e7a-8f22-279e4b4acb40.mov

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Number Play‬
URL: https://phet-dev.colorado.edu/html/number-play/1.0.0-rc.1/phet/number-play_all_phet.html?secondLocale=es
Version: 1.0.0-rc.1 2022-04-14 15:43:27 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15
Language: en-US
Window: 1403x701
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 256
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by KatieWoe** [comment]
I'm seeing this on Win 11 Firefox as well.

https://user-images.githubusercontent.com/41024075/163631919-f31c618d-a8e0-413c-a9ca-564264d7f2f2.MOV

**Comment by KatieWoe** [comment]
Oddly enough, iPadOS 15.4.1 Safari did not seem to have this issue.

**Comment by chrisklus** [comment]
hmm thanks yall. for more data points, it is working correctly on my Mac 10.13 Safari 13 and my Mac Firefox.

@Nancy-Salpepi @KatieWoe are you seeing `No voices found for locale: es` or something like that in the console when it's not working?

**Comment by KatieWoe** [comment]
Yup
<img width="929" alt="yup" src="https://user-images.githubusercontent.com/41024075/163649677-fffdcde6-88a0-4da7-b2ec-e5f27b086071.png">

**Comment by chrisklus** [comment]
Great, thanks. So either these browser versions don't have Spanish languages (in this case of using `es`), or the code we have to select a voice for a given locale is not correctly looking for a matching voice

**Comment by Nancy-Salpepi** [comment]
Oddly, nothing comes up in the console on the Mac.

**Comment by chrisklus** [comment]
Hm, that is odd. I don't think there's any thing we can do about this this morning before publishing the prototype, so I'm going to mark for final publication to continue investigation later. For the prototype, it would be nice to include on the sim page that Chrome best supports this feature.

**Comment by Nancy-Salpepi** [comment]
For https://github.com/phetsims/qa/issues/822 I still see this issue with Win10 FF in 1.1.0-dev.1. 
I can hear the Spanish speaking voice with Mac + safari.

**Comment by KatieWoe** [comment]
I repeated this on Win 11 Chrome. The correct words are read, but the wrong voice is used.

**Comment by jessegreenberg** [comment]
#204 is no longer blocking. I am wondering if this issue predated the little warning button that a language is not available:
![image](https://user-images.githubusercontent.com/6396244/213015089-0e2a883e-3d07-4a17-bb86-dec8d771ca6b.png)

That may be the solution to this one, unless its still happening in other cases.

**Comment by marlitas** [comment]
Yeah same observation as Jesse. My only thing is that now my `secondLocale=es` query parameter isn't working. I double checked but maybe I'm doing something wrong. @jessegreenberg and @chrisklus is that query parameter working for you?

**Comment by jessegreenberg** [comment]
It worked as I expected, but I had to use both `?locales=*&secondLocale=es`.

**Comment by marlitas** [comment]
Okay thanks that's user error on my part then. I thought I could do `locales=en&secondLocale=es` thanks for that correction @jessegreenberg. This seems like it is fixed and no longer an issue with the warning button mentioned above. Sending over to @chrisklus to confirm and close if that feels like the right call.

**Comment by chrisklus** [comment]
Thanks @jessegreenberg @marlitas - per what @jessegreenberg mentioned in https://github.com/phetsims/number-play/issues/160#issuecomment-1386069072, I think we are good to close. When we started dev testing, I'll make a note to keep an eye out for if there's ever a case where the voice doesn't work and there's no warning button.
