### ISSUE TITLE
gameLevels arguments should control info dialog

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-play#161]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/797.
When using the `?gameLevels` parameter to only show some of the levels, clicking on the info dialog in the game page still gives a description for all, even though some are hidden.

**Visuals**
![gamelevels](https://user-images.githubusercontent.com/41024075/163608029-68628c72-babc-4476-8349-dc5178f57c88.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Number Play‬
URL: https://phet-dev.colorado.edu/html/number-play/1.0.0-rc.1/phet/number-play_all_phet.html?gameLevels=1,2
Version: 1.0.0-rc.1 2022-04-14 15:43:27 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by chrisklus** [comment]
Thanks @KatieWoe - I discussed with @amanda-phet and she would like to see the behavior you're expecting. Since this is not a feature in FMW or Equality Explorer (other sims that use the standard `gameLevels` implementation), @amanda-phet would also like to open a vegas issue discuss adding this behavior elsewhere.

I'll do that today.

**Comment by amanda-phet** [comment]
Discussed in https://github.com/phetsims/vegas/issues/104 and we'd like to move forward with making a change here. So the `gameLevels` query parameter will control which levels are visible in the game info dialog, and only show the level descriptions for the visible levels.

**Comment by pixelzoom** [comment]
I don't know if this sim is PhET-iO instrumented yet.  But do make sure that `?gameLevels` controls visibility of the level descriptions, and does not conditionally create those descriptions.  That will ensure that `?gameLevels` does not change the PhET-iO API.

**Comment by chrisklus** [comment]
This functionality was added in https://github.com/phetsims/vegas/issues/104 and is working well, closing.
