### ISSUE TITLE
Should Reset All reset language toggle?

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-play#162]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/797
When using the `?secondLocale=es` parameter, the resulting toggle starts on English. If you switch it to Spanish and then hit Reset All the toggle stays on Spanish. This may be a desired behavior but it is different from typical sim behavior, so it should be confirmed if this is intended.

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Number Play‬
URL: https://phet-dev.colorado.edu/html/number-play/1.0.0-rc.1/phet/number-play_all_phet.html?secondLocale=es
Version: 1.0.0-rc.1 2022-04-14 15:43:27 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by chrisklus** [comment]
Thanks @KatieWoe! Yes it should, on it.

**Comment by chrisklus** [comment]
Fixed above, marking for cherry-picking.

**Comment by KatieWoe** [comment]
Looks good in https://phet-dev.colorado.edu/html/number-play/1.0.0-rc.2/phet/number-play_all_phet.html?secondLocale=es

**Comment by chrisklus** [comment]
Great, thanks! This was cherry-picked for https://github.com/phetsims/number-play/issues/166, closing.
