### ISSUE TITLE
Update credits

### ISSUE THREAD

**Issue by chrisklus** [phetsims/number-play#165]
No credits have been added yet.

**Comment by chrisklus** [comment]
Added above, marking for cherry-picking.

**Comment by KatieWoe** [comment]
Looks good in https://phet-dev.colorado.edu/html/number-play/1.0.0-rc.2/phet/number-play_all_phet.html?secondLocale=es

**Comment by chrisklus** [comment]
Awesome thanks! Closing.

**Comment by chrisklus** [comment]
Also, this was cherry-picked for https://github.com/phetsims/number-play/issues/166.
