### ISSUE TITLE
Update Number Play screenshots

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-play#168]
I just noticed my browser resize wasn't working right when I completed #163 , and the screenshots are the wrong size. It seems like they are working fine on the website for now, but I'll need to redo them for final publication.

**Comment by amanda-phet** [comment]
@KatieWoe is this something you or someone on the QA team could help me with today?

**Comment by amanda-phet** [comment]
Thank you @KatieWoe !

**Comment by amanda-phet** [comment]
These are ready to be cherry-picked in the next maintenance release

**Comment by chrisklus** [comment]
This was deployed to production, closing.
