### ISSUE TITLE
Able to drag objects out of empty box with touch

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-play#169]
**Test device**
Dell and iPad
**Operating System**
Win 11 and iPadOS 15
**Browser**
Chrome and Safari
**Problem description**
Found in https://github.com/phetsims/qa/issues/797
If you have removed all the objects from a toolbox (either numbers or objects) the pointer area is still there for touch. If you try to use a mouse to remove a new object nothing happens. If you use touch to remove a new object you can do this seemingly endlessly. The number displayed does not climb and it can lead to the sides having different numbers of objects. This is easiest to see on an iPad, but a computer with a touch screen will have this as well.
**Steps to reproduce**
1. Go to the Ten screen
2. Remove all the objects from the toolbox
3. Using touch, drag out another object from the box, even though it appears empty

**Visuals**

https://user-images.githubusercontent.com/41024075/165794027-a37e6e3e-60d8-4928-9e44-6d4daac098d2.MOV

![touchonly](https://user-images.githubusercontent.com/41024075/165794030-d42b4ad2-a0e7-4ccb-8f51-4b6739e76b2e.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Number Play‬
URL: https://phet-dev.colorado.edu/html/number-play/1.0.0-rc.1/phet/number-play_all_phet.html?showPointerAreas
Version: 1.0.0-rc.1 2022-04-14 15:43:27 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by chrisklus** [comment]
Thanks @KatieWoe - should be fixed in the commit above. Can you please test on phettest? Noting for ease of testing that Chrome's mobile viewing was able to reproduce this as well.

**Comment by KatieWoe** [comment]
Looks good on a quick check on master on Win 11 Chrome. The only potential oddity I found is this:
If you add all objects, take one away and add it back before the object reaches the tool box, then there will briefly be an extra object, however this quickly resolves itself and I don't think it is worth addressing.
Steps:
1. Go to the first screen and add all objects
2. Move numbers to top right of their area
3. Drag one of the objects to it's box, then immediately remove it before the corresponding number has reached its box

Visual
![newone](https://user-images.githubusercontent.com/41024075/166497998-81e9e256-1693-4129-9bfd-59de6b904f9d.gif)

**Comment by chrisklus** [comment]
Thanks @KatieWoe - the above behavior is as designed, but the 1 disappearing when it hits the panel is a little weird in my opinion. I may consider sending the returning one back out instead of returning it and adding a new one in a different issue. That would solve both minor problems you identified. This was deployed to production, closing.
