### ISSUE TITLE
Not all dogs lose their card when switching back to scene 1

### ISSUE THREAD

**Issue by chrisklus** [phetsims/number-play#171]
<img width="1382" alt="image" src="https://user-images.githubusercontent.com/5618316/169884458-b0f85e84-9214-40d2-a22b-c1aedfc720ae.png">

I recently discovered that you could get the object window in a state where not all objects lose their card when switching back to scene 1, as shown above. It is related to switching scenes + combining/separating cards. @KatieWoe if you are doing some extra testing on Number Play, could you please investigate to figure out the easiest way to reproduce this? Thanks!

**Comment by Nancy-Salpepi** [comment]
@chrisklus I was able to reproduce on the prototype (Bayes is down). 

Here are the some steps to reproduce:
1. On either the Ten or Twenty screen, add some dogs to the accordion box. 
2. Switch to scene 2. 
3. Combine two cards
4. Separate the two cards
5. Switch to scene 1


https://user-images.githubusercontent.com/87318828/169921726-7a804bcb-f726-4782-881c-24a76eeb6563.mp4

**Comment by chrisklus** [comment]
Thanks @Nancy-Salpepi! This ended up being a simple change, so I went ahead and maintenance released the fix and did some light testing. Could you please confirm on your end on the production version?

https://phet.colorado.edu/sims/html/number-play/latest/number-play_en.html

**Comment by Nancy-Salpepi** [comment]
@chrisklus I'm glad this was a simple change. All the dogs lose their card now. 

I noticed another bug while testing https://github.com/phetsims/number-play/issues/172.

Sorry we missed them initially.

**Comment by chrisklus** [comment]
Thanks @Nancy-Salpepi! Great, I'll check that out, and no worries! Closing here.
