### ISSUE TITLE
Cards don't look stacked when at top of accordion panel

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/number-play#172]
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.3.1

**Browser**
chrome

**Problem description**
Noticed when verifying https://github.com/phetsims/number-play/issues/171, if cards are combined at the top of the accordion panel, after switching back and forth between scenes 1 and 2, they will appear on top of one another instead of as a stack. 

**Steps to reproduce**
1. On either the Ten or Twenty screen, switch to scene 2 and add several dogs. 
2. Combine cards and move the cards so that they are at the top of the panel.
3. Switch to scene 1 and then back to scene 2.

**Visuals**

https://user-images.githubusercontent.com/87318828/170031942-c66f6a0d-04bb-4625-b62a-ba2078c689bd.mp4

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Number Play‬
URL: https://phet.colorado.edu/sims/html/number-play/latest/number-play_en.html
Version: 1.0.3 2022-05-24 03:06:35 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
Language: en-US
Window: 1257x639
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by chrisklus** [comment]
Thanks @Nancy-Salpepi! I think this is a side effect of needing to bump the group of cards down when the handle appears (put one at the top, then adding another to it bumps the group down). So the top card in the stack isn't placed where it wants to be which is causing the top 2 cards to be in the same position. 

I think a fix would be nice, but probably isn't necessary to MR for 1.0. Marking for 1.1.

**Comment by Nancy-Salpepi** [comment]
@chrisklus I noticed that if you then switch back to scene 1 again, the dogs will also be on top of each other. It makes it look like there are the wrong number of dogs present. 
For example, in the pic below, you only see 9 dogs.
<img width="705" alt="Screen Shot 2022-05-24 at 3 58 57 PM" src="https://user-images.githubusercontent.com/87318828/170121881-547766b7-5d74-40de-88d4-1402e0472f08.png">

**Comment by pixelzoom** [comment]
Simpliest case to produce:

1. Got to Tens screen
2. Put 2 dogs in right play area
3. Switch to grouped radio button
4. Combine the 2 dogs
5. Move the combined dogs to top of accordion box, like this:

<img width="435" alt="screenshot_2123" src="https://user-images.githubusercontent.com/3046552/211366020-4c963392-d48b-4ac0-91b2-4e337368e486.png">

6. Switch to ungrouped radio button. 
7. Swtich to grouped radio button. The 2 cards will be on top of each other, like this:

<img width="435" alt="screenshot_2124" src="https://user-images.githubusercontent.com/3046552/211366036-3d41601d-73f5-44bb-91a0-8a1c6db008b0.png">

**Comment by pixelzoom** [comment]
@chrisklus and I worked on this.

The problem is not specific to breaking apart groups.  It's when we switch group ungrouped to grouped, moving 1 of the object (in this case, the one that needs to be shifted down to add the card background) results in overlapping cards.  We think the best place to address this is in CountingPlayArea.ts, where I've put the TODO here:

```diff
    this.groupingEnabledProperty.lazyLink( groupingEnabled => {
      !groupingEnabled && this.breakApartCountingObjects( true );
+      if ( groupingEnabled ) {
+        //TODO make sure no 2 counting objects have the same position
+      }
    } );
``` 

I'll take from here...

**Comment by pixelzoom** [comment]
I tried the approach we identified in https://github.com/phetsims/number-play/issues/172#issuecomment-1375999692.  Unfortunately it does not address the issue.  I suspect that the position is being adjusted later by the model, so this code is not effective. 

For posterity, here's what I tried:

<details>
<summary>patch</summary>

```diff
Index: number-suite-common/js/common/model/CountingPlayArea.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/number-suite-common/js/common/model/CountingPlayArea.ts b/number-suite-common/js/common/model/CountingPlayArea.ts
--- a/number-suite-common/js/common/model/CountingPlayArea.ts	(revision 0de0ed5e0fdd711229f2ed778f81bde5ce8e8ff3)
+++ b/number-suite-common/js/common/model/CountingPlayArea.ts	(date 1673290631399)
@@ -77,6 +77,23 @@
 
     this.groupingEnabledProperty.lazyLink( groupingEnabled => {
       !groupingEnabled && this.breakApartCountingObjects( true );
+      if ( groupingEnabled ) {
+
+        // Sort objects from top to bottom position
+        const countingObjects = _.sortBy( this.countingObjects, countingObject => countingObject.positionProperty.value.y );
+
+        // Prevent occlusion of cards that have the same position.
+        for ( let i = 0; i < countingObjects.length - 1; i++ ) {
+          const countingObject = countingObjects[ i ];
+          for ( let j = i + 1; j < countingObjects.length; j++ ) {
+            const nextCountingObject = countingObjects[ j ];
+            if ( nextCountingObject.y === countingObject.y ) {
+              console.log( 'occlusion detected, shifting y' );
+              nextCountingObject.y = nextCountingObject.y + 10; //TODO magic number
+            }
+          }
+        }
+      }
     } );
   }
 
Index: counting-common/js/common/model/CountingObject.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/counting-common/js/common/model/CountingObject.ts b/counting-common/js/common/model/CountingObject.ts
--- a/counting-common/js/common/model/CountingObject.ts	(revision af676d3e5561d9bc8f076dc620c79c07b8ecfab4)
+++ b/counting-common/js/common/model/CountingObject.ts	(date 1673290259968)
@@ -121,6 +121,14 @@
     this.returnAnimationBounds = this.localBounds;
   }
 
+  public get y(): number {
+    return this.positionProperty.value.y;
+  }
+
+  public set y( value: number ) {
+    this.positionProperty.value = new Vector2( this.positionProperty.value.x, value );
+  }
+
   /**
    * The number of digits in the number, including zeros, e.g. 1204 has 4 digits.
    */
```

</details>

**Comment by pixelzoom** [comment]
As mentioned in https://github.com/phetsims/number-play/issues/172#issuecomment-1375999692:
> The problem is not specific to breaking apart groups. It's when we switch group ungrouped to grouped ...

Here are better steps to reproduce:

1. Go to the Tens screen
2. Put 2 dogs in right play area
3. Move the 2 dogs to the top of the accordion box, like this:
<img width="438" alt="screenshot_2125" src="https://user-images.githubusercontent.com/3046552/211389527-cf08d05f-6e67-4c3c-a1a2-f3961a764ad5.png">

4. Switch to grouped radio button. The 2 cards overlap, like this:
<img width="438" alt="screenshot_2126" src="https://user-images.githubusercontent.com/3046552/211389596-30bf7fda-df52-4f9e-892c-3999ab7717b5.png">

5. Switch back to ungrouped radio button. The 2 dogs still overlap, like this:
<img width="436" alt="screenshot_2127" src="https://user-images.githubusercontent.com/3046552/211389669-9c2fb349-1b9e-4d77-9bdc-00b935614b04.png">

So the problem is unrelated to CountingPlayArea `breakApartCountingObjects`.

**Comment by pixelzoom** [comment]
I identified where the counting object's position is being adjusted. Unfortunately it's in CountingObjectNode.ts.  Here's how I verified:

```diff
    this.countingObjectTypeAndGroupTypeListener = ( countingObjectType: CountingObjectType, groupingEnabled: boolean ) => {
      this.updateNumber();

      if ( !countingObject.isAnimating ) {
        const destination = countingObject.positionProperty.value;
        countingObject.setConstrainedDestination( this.availableViewBoundsProperty.value, destination );
+       if ( !countingObject.positionProperty.value.equals( destination ) ) {
+         console.log( `countingObject position was constrained from ${destination} to ${countingObject.positionProperty.value}` );
+       }
      }
    };
```

Can here's the console output for the scenario described in https://github.com/phetsims/number-play/issues/172#issuecomment-1376158177:

> countingObject position was constrained from Vector2(193.46586854408707, 3.889999999999997) to Vector2(193.46586854408707, 10)
> countingObject position was constrained from Vector2(193.46586854408707, 9.587272727272724) to Vector2(193.46586854408707, 10)

**Comment by pixelzoom** [comment]
This problem is bigger than this one case.  The view (CountingObjectNode) is responsible for constraining the position of the model (CountingObjects), and does so without considering the position of any of the other CountingObjects in the model. So in general, there's nothing that prevents the constrained position from overlapping with the position of some other CountingObject.  Something needs to responsible for ensuring that CountingObjects do not overlap.  And I'm not sure where that responsibility should live, and how it should be notified.

@chrisklus thoughts?

**Comment by chrisklus** [comment]
I tried out other possibilities that were based more of the model as proposed in https://github.com/phetsims/number-play/issues/172#issuecomment-1375999692 but could not get anything to work nicely because of the way that the view needs to change from a grouping state change first before repositioning can happen in the model since the view style determines the model bounds. @pixelzoom and I discussed more and concluded that his solution was best for the time that we have. I think this is all set, closing.

**Comment by chrisklus** [comment]
Oh dear, thanks @Nancy-Salpepi! @zepumph and I have been working on this over the past day. Here's a patch that continues in a direction of a workaround already in place from the original problem in this issue:

<details>

```diff

Index: number-suite-common/js/common/view/CountingPlayAreaNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/number-suite-common/js/common/view/CountingPlayAreaNode.ts b/number-suite-common/js/common/view/CountingPlayAreaNode.ts
--- a/number-suite-common/js/common/view/CountingPlayAreaNode.ts	(revision 3c96db2e5da075329ff0f85208f9aa2a5723c501)
+++ b/number-suite-common/js/common/view/CountingPlayAreaNode.ts	(date 1680113156220)
@@ -546,15 +546,21 @@
    * shifting it down. This is a workaround for https://github.com/phetsims/number-play/issues/172.
    */
   private preventOcclusion( countingObject: CountingObject ): void {
-    const countingObjects = this.playArea.countingObjects;
+    const countingObjects = this.playArea.getCountingObjectsIncludedInSum();
     for ( let i = 0; i < countingObjects.length - 1; i++ ) {
       const nextCountingObject = countingObjects[ i ];
       if ( nextCountingObject !== countingObject ) {
-        if ( nextCountingObject.positionProperty.value.y === countingObject.positionProperty.value.y ) {
+        if ( nextCountingObject.positionProperty.value.distance( countingObject.positionProperty.value ) < 2 ) {
           countingObject.positionProperty.value = new Vector2(
             countingObject.positionProperty.value.x,
             countingObject.positionProperty.value.y + CountingCommonConstants.BREAK_APART_Y_OFFSET
           );
+
+          const countingObjectNode = this.getCountingObjectNode( countingObject );
+          console.log( `${countingObject.id} moved from preventOcclusion to ${countingObject.positionProperty.value.y}, emitting to move again` );
+          // debugger;
+          countingObject.moveToFrontEmitter.emit();
+          countingObjectNode.positionConstrainedEmitter.emit( countingObject );
           break;
         }
       }
Index: number-suite-common/js/common/model/CountingPlayArea.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/number-suite-common/js/common/model/CountingPlayArea.ts b/number-suite-common/js/common/model/CountingPlayArea.ts
--- a/number-suite-common/js/common/model/CountingPlayArea.ts	(revision 3c96db2e5da075329ff0f85208f9aa2a5723c501)
+++ b/number-suite-common/js/common/model/CountingPlayArea.ts	(date 1680113611744)
@@ -87,6 +87,7 @@
     // when grouping is turned off, break apart any object groups
     this.groupingEnabledProperty.lazyLink( groupingEnabled => {
       !groupingEnabled && this.breakApartCountingObjects( true );
+
     } );
 
     this.countingObjects.addItemRemovedListener( countingObject => { countingObject.dispose(); } );
Index: counting-common/js/common/view/CountingObjectNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/counting-common/js/common/view/CountingObjectNode.ts b/counting-common/js/common/view/CountingObjectNode.ts
--- a/counting-common/js/common/view/CountingObjectNode.ts	(revision a7a230f9942c0fb5ecda49b584cb9bcfb2f31cc3)
+++ b/counting-common/js/common/view/CountingObjectNode.ts	(date 1680113003125)
@@ -235,8 +235,11 @@
         const destination = countingObject.positionProperty.value;
         countingObject.setConstrainedDestination( this.availableViewBoundsProperty.value, destination );
 
+        console.log( `tried to constrain ${countingObject.id} with y-position: ${countingObject.positionProperty.value.y}` );
+
         // If countingObject's actual position differs from the destination that we specified, notify listeners.
         if ( !countingObject.positionProperty.value.equals( destination ) ) {
+          console.log( `${countingObject.id} constrained from ${destination.y} to ${countingObject.positionProperty.value.y}` );
           this.positionConstrainedEmitter.emit( countingObject );
         }
       }
@@ -248,6 +251,11 @@
     countingObject.moveToFrontEmitter.addListener( () => {
       this.moveToFront();
     } );
+
+    // assert that positionConstrainedEmitter is called for our own model.
+    assert && this.positionConstrainedEmitter.addListener( o => {
+      assert!( countingObject === o, 'positionConstrainedEmitter called for non-matching countingObject' );
+    } );
   }
 
   /**

```

</details>

We are also going to try fixing this higher up to omit this workaround.

**Comment by chrisklus** [comment]
We think we got it! @Nancy-Salpepi could you please test on phettest? Please note are not that concerned with finding corner cases where the user can manually create a situation to cover up another counting object because we are aware that is still possible - for this issue, we would just like to fix the cases where clicking between states creates a problem (like your example in https://github.com/phetsims/number-play/issues/172#issuecomment-1483318153).

We are also excited to have removed an earlier workaround that was added in this issue to try to fix the original problem.

**Comment by Nancy-Salpepi** [comment]
This looks good in master! Closing! 🥳
