### ISSUE TITLE
Unintentional overlap of objects

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-play#180]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/822
It is possible to get non-card objects to fully overlap with each other fairly easily. If you overlap two in a corner, then overlap a third, the movements trying to prevent overlap will cause overlap with another object. This may not be worth addressing, but I wanted to document it just in case.
**Steps to reproduce**
1. Go to a screen and scene with non-card objects
2. Put one object in the corner of the play area
3. Take a second object and overlap it with the first (the second should move slightly)
4. Take a third object and overlap it with the first (it will jump to overlap the second)

**Visuals**
![overlaps](https://user-images.githubusercontent.com/41024075/181832951-9a846d10-53bc-4f25-8e16-10cda10424e7.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Number Play‬
URL: https://phet-dev.colorado.edu/html/number-play/1.1.0-dev.1/phet/number-play_all_phet.html
Version: 1.1.0-dev.1 2022-07-28 23:33:39 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by Nancy-Salpepi** [comment]
This happens on the Ten and Twenty screens as well

https://user-images.githubusercontent.com/87318828/181916061-ce093971-721f-4121-9132-95d87e66fa22.mp4

**Comment by amanda-phet** [comment]
I would say it's a known issue. We've discussed it in the context of the Lab screen, and it is something I am ok with leaving as-is.

**Comment by chrisklus** [comment]
@amanda-phet and I confirmed this as a won't-fix and decided to close, thanks all.
