### ISSUE TITLE
Value changes to 1 before returning to collection area

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/number-play#182]
**Test device**
MacBook Air (m1 chip)

**Operating System**
macOS 12.5

**Browser**
safari 15.5

**Problem description**
For https://github.com/phetsims/qa/issues/822, if I combine all the paper 1's to make one number (ex-6) and then return a group of objects to the collection area (ex-6 dogs on a card), the number 6 changes to a 1 before if returns to the collection area. I thought this was a bit odd, but I'm not sure if it was intentional or not. It is also present in the Prototype version.

**Steps to reproduce**
1. On the Ten or Twenty screen, add six paper 1's to the play area. 
2. Combine all paper 1's to make a 6
3. Switch to the second scene--cards
4. Combine all dogs on one card
5. Return the dog card to the collection area--the number 6 changes to a 1 in the left play area before returning
*the reverse will also happen: If you return the 6, the 6 dogs change to 1 dog before returning to the collection area

**Visuals**

https://user-images.githubusercontent.com/87318828/181924558-2bd46fe4-8c02-48a8-ae7d-f1ff3dbf5858.mp4

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Number Play‬
URL: https://phet-dev.colorado.edu/html/number-play/1.1.0-dev.1/phet/number-play_all_phet.html
Version: 1.1.0-dev.1 2022-07-28 23:33:39 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6 Safari/605.1.15
Language: en-US
Window: 1322x704
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by amanda-phet** [comment]
I wonder if it's actually a stack of 1's, because the 9 breaks up into 1's when the butterfly group is returned, but we can only see the top one. I agree it looks strange though, and would be nice if there was a way around that behavior.

**Comment by chrisklus** [comment]
@pixelzoom I'll update this with another comment before you take a look

**Comment by pixelzoom** [comment]
@chrisklus demonstrated and explained this to me.

If dragging a card back to the creator panel on left side... If a card on the right side needs to be broken apart, or the entire card returned, then show a grouped card returning to the creator panel on the right side.

If dragging a card back to the creator panel on right side... If a number of the left side needs to be broken apart, or the entire number returned, then show the entire number returning to the creator panel on the left side.

See `returnCountingObjectToBucket` in CountingPlayArea.ts.

**Comment by chrisklus** [comment]
Adding blocks-sim-publication label to indicate this should be completed before starting dev testing.

**Comment by chrisklus** [comment]
@marlitas and I had a great time today writing a recursive algorithm for this change! We got the behavior working exactly as we intended and are excited with what we came up with to do so.

@pixelzoom could you please review at your convenience? Relevant code to review is in `CountingPlayArea.returnCountingObjectToCreatorNode`. Further cleanup for other parts of this file is still to happen in https://github.com/phetsims/number-suite-common/issues/12.

**Comment by pixelzoom** [comment]
This seems to behave as desired, and code is well-documented.

Two bits of feedback:

(1) Is your recursive algorithm is guaranteed to finish? I can't tell...  A common flaw in recursive algorithms is that they can accidentally recurse infinitely.  A best pratice is to have something that explicitly prevents infinite recursion, and/or document how the algorithm (code) prevents infinite recursion.

(2) `recursivelyFindBestMatches` has 3 `return` statements. That's 2 `return` statements too many, especially in a function that uses recursion.  Recommended patch (untested):

<details>
<summary>patch</summary>

```diff
Subject: [PATCH] allow tool subclasses to customize what is featured, https://github.com/phetsims/calculus-grapher/issues/225
---
Index: js/common/model/CountingPlayArea.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/model/CountingPlayArea.ts b/js/common/model/CountingPlayArea.ts
--- a/js/common/model/CountingPlayArea.ts	(revision 75d67f9cb6002bc89b031fef5df4c6f0cda57477)
+++ b/js/common/model/CountingPlayArea.ts	(date 1678970062657)
@@ -238,11 +238,13 @@
      */
     const recursivelyFindBestMatches = ( value: number, sortedCountingObjects: CountingObject[] ): CountingObject[] => {
 
+      let bestMatches: CountingObject[];
+
       // First, see if there are any countingObjects with the same value. If so, we are done.
       for ( let i = 0; i < sortedCountingObjects.length; i++ ) {
         const countingObject = sortedCountingObjects[ i ];
         if ( countingObject.numberValueProperty.value === value ) {
-          return [ countingObject ];
+          bestMatches = [ countingObject ];
         }
       }
 
@@ -265,13 +267,15 @@
         // a part of the next search.
         _.remove( sortedCountingObjects, largestCountingObject );
 
-        return [ largestCountingObject, ...recursivelyFindBestMatches( nextValueToReturn, sortedCountingObjects ) ];
+        bestMatches = [ largestCountingObject, ...recursivelyFindBestMatches( nextValueToReturn, sortedCountingObjects ) ];
       }
       // If the value we're looking for is smaller than the largestCountingObject, create a new countingObject by
       // breaking off the value we need from the largest one.
       else {
-        return [ this.splitCountingObject( largestCountingObject, value ) ];
+        bestMatches = [ this.splitCountingObject( largestCountingObject, value ) ];
       }
+
+      return bestMatches;
     };
 
     const countingObjectsToReturn = recursivelyFindBestMatches( valueToReturn, sortedCountingObjects );
```

</details>

**Comment by marlitas** [comment]
I haven't had a chance to test the patch yet, but the first red flag I see is that we will no longer be returning the closest counting object if there are multiple exact matches. 

The return statement in the first for loop ensured that we break out of the loop as soon as we find a match (sorted by distance). By continuing the for loop, if there are multiple matches we will actually return the furthest matching countingObject. 

We might be able to fix this scenario by adding a second conditional in the for loop, or replacing with a while loop, but haven't had a chance to dig in yet. Can do so in a bit and report back.

**Comment by marlitas** [comment]
Okay. I cleaned things up to demonstrate the the recursive function will indeed finish, and also reduced to a singular return statement. @pixelzoom Let me know how it looks, changes done in the above commit.

**Comment by pixelzoom** [comment]
👍🏻 Looks great, closing.
