### ISSUE TITLE
Create a new common code repo to share code with make-a-ten

### ISSUE THREAD

**Issue by samreid** [phetsims/number-play#19]
@chrisklus and I recommend generalizing code in make-a-ten for reuse in number play.  Currently, number-play has a dependency on make-a-ten, but that sim->sim dependency is not desirable for the long run.  So we would like to factor out common code from make-a-ten for reuse.

We were originally going to call the new repo “make-a-ten-common” but realized that is not very general.  We aren’t making tens in number play.  We considered “paper-numbers” but that’s not a good fit either because some of the representations are shown without paper or any background.  We considered “counting-objects” “combining-numbers” but aren’t really happy with either of those. 

I reached out to @jonathanolson on slack about what to name the new repo.

**Comment by samreid** [comment]
We ran a webpack build with 

```
node node_modules/webpack/bin/webpack.js --display-modules --entry ../number-play/js/number-play-main.js
```

to see which parts of make a ten are currently used, it reported:
* make-a-ten/common/view/BaseNumberNode.js
* make-a-ten/common/model/BaseNumber.js
* make-a-ten/common/model/PaperNumber.js
* make-a-ten/common/MakeATenConstants.js
* make-a-ten/common/MakeATenUtils.js
* make-a-ten/common/model/ArithmeticRules.js

We also saw these files which seem copied from make-a-ten:
* BaseNumberNode
* OnesCreatorNode
* OnesPlayArea
* OnesPlayAreaNode
* PaperNumberNode

**Comment by samreid** [comment]
In slack, @jonathanolson said:

> Sounds fine to move to its own repo, I forget the original reasoning behind [avoiding sim=>sim dependencies] but it also makes maintenance-releasing multi-sim code a bit easier

**Comment by samreid** [comment]
Regarding the name, @jonathanolson said:

> counting-common, combining-common are also options? Otherwise I'm fine with any of the above names you suggested

@chrisklus what do you recommend?

**Comment by chrisklus** [comment]
The vast majority of this work was completed. The remaining file in Number Play that duplicates code from Make a Ten will be worked on later in https://github.com/phetsims/number-play/issues/119.

**Comment by samreid** [comment]
As discovered in https://github.com/phetsims/chipper/issues/946, there are TODOs in the code referring to this issue.  Reopening.

**Comment by pixelzoom** [comment]
There is 1 TODO in the code that needs to be addressed.  In CountingPlayAreaNode.ts:

```typescript
        if ( draggedCountingObject.positionProperty.value.distance( droppedCountingObject.positionProperty.value ) < 7 ) { // TODO: https://github.com/phetsims/number-play/issues/19 match this with the card object spacing
```

It's not clear to me what that code and comment is related to this issue. Perhaps it's the wrong issue number in the TODO comment?

**Comment by chrisklus** [comment]
>It's not clear to me how that code and comment is related to this issue. I suspect that the wrong issue number is used in the TODO comment.

I agree. The repel distance has been looking nice, so I made it a constant and removed the TODO. Closing.
