### ISSUE TITLE
Use “Ten Frames” (plural) for the accordion box title in “Twenty” screen

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-play#192]
From https://github.com/phetsims/number-suite-common/issues/3:

>  - [ ] Should we use “Ten Frames” (plural) for the accordion box title in “Twenty” screen? (effort: trivial)

@amanda-phet replied:

> That sounds fine.

I'll knock this one off.

**Comment by pixelzoom** [comment]
Done in the above commits.

Ten screen:
<img width="379" alt="screenshot_2105" src="https://user-images.githubusercontent.com/3046552/210464245-0c3ab59b-fc97-4c7d-b38f-3891be4efad9.png">

Twenty screen:
<img width="383" alt="screenshot_2106" src="https://user-images.githubusercontent.com/3046552/210464261-dcbd4ffa-1cc2-4ed3-b062-7680571ed37f.png">

Over to @chrisklus to review. Feel free to close.

**Comment by chrisklus** [comment]
Looks great, thanks!
