### ISSUE TITLE
Non-standard "yellow" color for  buttons

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-play#193]
In the Game, the color for the "Play" button and "New Challenge" buttons is `Color.YELLOW`.   That violates the standard of using `PhetColorScheme.BUTTON_YELLOW`.  I'm going to change to the standard. 

This is also related to https://github.com/phetsims/number-suite-common/issues/7, where Color.YELLOW was incorrectly being used for the back button in the Game status bar.

**Comment by pixelzoom** [comment]
Similar problem for the SpeechSynthesisButton.

**Comment by pixelzoom** [comment]
Since I've found 4 places that are using Color.YELLOW instead of PhetColorScheme.BUTTON_YELLOW, I'm going to clear this with @amanda-phet before making any changes.

@amanda-phet Did you intentionally specify Color.YELLOW instead of PhetColorScheme.BUTTON_YELLOW?  If so, why is the standard color not appropriate for this sim?

**Comment by amanda-phet** [comment]
>@amanda-phet Did you intentionally specify Color.YELLOW instead of PhetColorScheme.BUTTON_YELLOW? If so, why is the standard color not appropriate for this sim?

I did not. Thanks for checking! It is OK with me to follow through with changing Color.YELLOW to PhetColorScheme.BUTTON_YELLOW.

**Comment by pixelzoom** [comment]
Thanks @amanda-phet.  I switched to PhetColorSchema.BUTTON_YELLOW where appropriate in the above commits.  Assigning to @chrisklus so that he's aware of this change, feel free to close.

**Comment by chrisklus** [comment]
Thanks @pixelzoom, changes look good. I didn't know `PhetColorSchema.BUTTON_YELLOW` existed. Closing.
