### ISSUE TITLE
"Word" accordion box is not initialized properly

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-play#194]
The contents of the "Word" accordion box do not seem to be initialized properly.  It's initially empty.

To reproduce:

1. Run number-play
2. Go to the Ten screen
3. Expand the "Word" accordion box. Note that it's empty.
4. Increment the Total spinner from 0 to 1.
5. Decrement the Total spinner from 1 to 0.
6. Note that the "Word" accordion box now displays "zero".

@chrisklus Can you confirm whether this is a bug or expected behavior?

**Comment by pixelzoom** [comment]
This appears to be the culprit in WordAccordionBox. Because it's a `Multilink.lazyMultilink`, its not called until the value changes.  Should it be `Multilink.multilink`?

```typescript
    // update the word if the current number or locale changes
    Multilink.lazyMultilink( [ currentNumberProperty, isPrimaryLocaleProperty ],
      ( currentNumber, isPrimaryLocale ) => {
        wordText.text = NumberSuiteCommonConstants.numberToString( numberPlayPreferences.secondLocaleStringsProperty.value,
          currentNumber, isPrimaryLocale );
      } );
```

**Comment by pixelzoom** [comment]
I went ahead and changed to `Multilink.multilink`.  @chrisklus please review.

**Comment by chrisklus** [comment]
Thanks @pixelzoom. This bug was introduced recently in https://github.com/phetsims/number-play/commit/50f1be07f6ab2f1c7aa3024f5c9f68a614a3a9c7, where I got rid of the initial text value and didn't notice that `Multilink.lazyMultilink` was being used. Changes look great and it's working well on my end. Closing.
