### ISSUE TITLE
Each screen should have top-level model and view classes

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-play#196]
This was confusing to me when browsing the code. And it's still causing me problems when investigating issues.  For example, when I want to investigate a view problem in the Ten screen, I expect to navigate to TenScreenView, but it does not exist.

Typically each screen should have a ScreenView subclass, and a class that implements TModel.  Instead, this sim has a bunch of code in each Screen subclass that instantiates the base classes NumberPlayScreenView and NumberPlayModel. 

For example, in TenScreen:

```typescript
  const screenViewOptions: NumberPlayScreenViewOptions = { 
     ... // LOTS of options!
  };
...
    super(
      () => new NumberPlayModel(
        NumberPlayConstants.TEN,
        tandem.createTandem( 'model' )
      ),
      model => new NumberPlayScreenView( model, screenViewOptions ),
      screenOptions
    );
```

So I'm going to factor out ScreenView and TModel classes for each screen.

**Comment by pixelzoom** [comment]
Summary of the above commits:
* added model and view classes for the Ten and Twenty screens
* made NumberPlayScreenView `protected constructor` since it's now a base class
* made NumberPlayModel `protected constructor` since it's now a base class
* added missing `implements TModel` to model classes

Over to @chrisklus for review, feel free to close.

**Comment by chrisklus** [comment]
Thanks for this improvement, changes look great. Closing.
