### ISSUE TITLE
Credits for 1.1

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-play#201]
Complete credits for 1.0 release.   QA credits will not be finalized until after final RC test.

Should credits be shared with number-compare-main.ts?

**Comment by marlitas** [comment]
@pixelzoom and I talked about how the credits between Number Play and Number Compare will begin to diverge during dev test, as well as how they will most likely be completely different for Number Pairs. In this case factoring out credits does not seem necessary, and the amount of duplication will be minimal between the three sims. I'm going to revert the above commits.

**Comment by marlitas** [comment]
@KatieWoe and @amanda-phet we are unsure if the credits here are accurate. Can you double check with the understanding QA credits may change once we go through dev testing? 

```
leadDesign: 'Amanda McGarry',
softwareDevelopment: 'Chris Klusendorf, Luisa Vargas',
team: 'Sylvia Celedón-Pattichis, Ariel Paul, Kathy Perkins, Ian Whitacre, Chris Malley (PixelZoom, Inc.), Marla Schulz, Michael Kauzmann',
qualityAssurance: 'Clifford Hardin, Emily Miller, Nancy Salpepi, Kathryn Woessner',
graphicArts: 'Mariah Hermsmeyer',
thanks: 'Andrea Barraugh (Math Transformations), Kristin Donley, Bertha Orona'
```

**Comment by pixelzoom** [comment]
> ... with the understanding QA credits may change once we go through dev testing?

FYI... Credits typically change throughout the QA process, including after RC tests, and right up until we publish.

**Comment by pixelzoom** [comment]
> ... with the understanding QA credits may change once we go through dev testing?

FYI... Credits typically change throughout the QA process, including after RC tests, and right up until we publish.  And they need to be confirmed just before we publish.  So this issue most definitely blocks publication, until @KatieWoe gives the final revisions and sign-off.

**Comment by KatieWoe** [comment]
They're ok for now, but like @pixelzoom said, they may change

**Comment by marlitas** [comment]
Sounds good. Sorry about removing that label @pixelzoom I was thinking about a recent meeting where we were saying block-publication will be blocking the dev test for NP, but perhaps this is safe to assume we can move forward.

**Comment by amanda-phet** [comment]
We usually alphabetize by last name, so I would update that. I'm also adding @catherinecarter since she did interviews with me.  

Catherine Carter, Sylvia Celedón-Pattichis, Michael Kauzmann, Chris Malley (PixelZoom, Inc.), Ariel Paul, Kathy Perkins, Marla Schulz, Ian Whitacre

**Comment by marlitas** [comment]
Made those changes @amanda-phet. Moving this to done in the Pistachio board as the needs for this issue prior to dev test have been met.

**Comment by chrisklus** [comment]
@marlitas I would prefer to keep issues that may still need to be worked on for this publication out of the Done column. There are other issues that won't be worked on before starting a dev test that are staying in the Todo column, not being moved to Done.

**Comment by chrisklus** [comment]
Although now I'm realizing that doesn't really make sense given pistachios goal for this sim for the month. I'm not sure what's going to happen to this project board after tomorrow.

**Comment by Nancy-Salpepi** [comment]
Please add Jaron Droder and Martin Veillette to QA credits.

**Comment by chrisklus** [comment]
Thanks @Nancy-Salpepi, this is ready for review on phettest. I also added @zepumph.

**Comment by Nancy-Salpepi** [comment]
Looks good.

**Comment by chrisklus** [comment]
Thanks! Patch applied above

**Comment by zepumph** [comment]
QA feel free to close after confirming this in the new RC.

**Comment by Nancy-Salpepi** [comment]
Looks good in rc.2
