### ISSUE TITLE
Sim freezes when attempting to select a second locale with some untranslated strings

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/number-play#205]
With macOS 13.1 and safari 16.1 (also with the iPad), in master using locales=* if I try to select a second locale where some strings aren't translated, the sim freezes and I see an assertion error:
<img width="1335" alt="Screenshot 2023-01-17 at 7 18 28 PM" src="https://user-images.githubusercontent.com/87318828/213048909-068bf4b7-7b2a-4d82-9438-16e0286ebb58.png">

I didn't try a lot of languages, but saw it with Welsh and espanol (Espana).

**Comment by chrisklus** [comment]
Thanks @Nancy-Salpepi! I think this is the same issue as https://github.com/phetsims/number-suite-common/issues/13, so I'm going to close as a duplicate :)
