### ISSUE TITLE
Revise keys in number-play-strings_en.json

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-play#206]
Similar to https://github.com/phetsims/number-compare/issues/14 ...

In number-play-strings_en.json, this string key is not quite right. It should be "hearTotal".

```
"readAloud": {
    "value": "Hear Total"
  },
```

It should also be consistent with number-compare, where this change was made:

```diff
- "readAloud": {
+ "hearNumberSentence": {
    "value": "Hear Number Sentence"
  }
```

Since Number Play 1.0 was a prototype, and we've introduced other new strings, I'm going to assume that it's OK to change this string key.

**Comment by pixelzoom** [comment]
Done in the above commit. @chrisklus please view. Close if OK.

**Comment by chrisklus** [comment]
Changes look great, thanks @pixelzoom!
