### ISSUE TITLE
Should the ten frames on the Twenty screen match the layout of the organized objects?

### ISSUE THREAD

**Issue by chrisklus** [phetsims/number-play#208]
@marlitas and @pixelzoom were bummed that on the Twenty screen, the ten frames have a 10 x 2 arrangement, while the counting objects have a 5 x 4 arrangement. While there isn't a ton we can do about this because of space constraints, they suggested shrinking the ten frames and stacking them on top of each other could be a possibility. Assigning to @amanda-phet to weigh in.

**Comment by pixelzoom** [comment]
Self assigning to play with what a vertical layout of 2 ten frames would look like.  Should be a matter of changing an HBox to a VBox and adjusting some margins/spacing in TenFrameNode?

**Comment by pixelzoom** [comment]
Here's what the Twenty screen looks like if the Ten Frames are stacked vertically, to match the layout of objects in the accordion box. This doesn't look bad or cramped to me, and the correlation with the layout of the accordion box is lightyears better.

<img width="1082" alt="screenshot_2248" src="https://user-images.githubusercontent.com/3046552/216169078-29134aa0-c0f6-4d6d-a95f-12b931f613d7.png">


Here's a patch that I used to create the above screenshot. Note that this patch does not address the use of TenFrameNode in the Game screen (CountingGameLevelNode.ts).

<details>
<summary>patch</summary>

```diff
Subject: [PATCH] revert unintended change, https://github.com/phetsims/number-play/issues/208
---
Index: number-play/js/common/view/TenFrameAccordionBox.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/number-play/js/common/view/TenFrameAccordionBox.ts b/number-play/js/common/view/TenFrameAccordionBox.ts
--- a/number-play/js/common/view/TenFrameAccordionBox.ts	(revision 606c2dcf3d121af0a4d7bf696b01f71562db99a6)
+++ b/number-play/js/common/view/TenFrameAccordionBox.ts	(date 1675286242012)
@@ -47,7 +47,7 @@
 
     super( NumberPlayConstants.UPPER_OUTER_ACCORDION_BOX_WIDTH, new Property<number>( height ), options );
 
-    tenFrameNode.scale( height / tenFrameNode.height / 2 );
+    tenFrameNode.scale( height / tenFrameNode.height / 1.15 );
     tenFrameNode.centerX = this.contentBoundsProperty.value.centerX + options.tenFrameOffsetX;
     tenFrameNode.centerY = this.contentBoundsProperty.value.centerY;
     this.contentNode.addChild( tenFrameNode );
Index: number-suite-common/js/common/view/TenFrameNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/number-suite-common/js/common/view/TenFrameNode.ts b/number-suite-common/js/common/view/TenFrameNode.ts
--- a/number-suite-common/js/common/view/TenFrameNode.ts	(revision b3e13c88c7f0d598f71341165a1bea8d415269fd)
+++ b/number-suite-common/js/common/view/TenFrameNode.ts	(date 1675287343236)
@@ -11,7 +11,7 @@
 
 import Vector2 from '../../../../dot/js/Vector2.js';
 import { Shape } from '../../../../kite/js/imports.js';
-import { Circle, HBox, Node, PaintableOptions, Path } from '../../../../scenery/js/imports.js';
+import { Circle, Node, PaintableOptions, Path, VBox } from '../../../../scenery/js/imports.js';
 import numberSuiteCommon from '../../numberSuiteCommon.js';
 import NumberSuiteCommonConstants from '../NumberSuiteCommonConstants.js';
 import TReadOnlyProperty from '../../../../axon/js/TReadOnlyProperty.js';
@@ -59,8 +59,8 @@
       tenFramePaths.push( TenFrameNode.getTenFramePath() );
     } );
 
-    // add all ten frames, aligned in a horizontal line
-    const alignedTenFrames = new HBox( {
+    // add all ten frames, aligned vertically
+    const alignedTenFrames = new VBox( {
       children: tenFramePaths,
       spacing: DISTANCE_BETWEEN_TEN_FRAMES
     } );
@@ -107,17 +107,17 @@
     const squareCenterOffset = options.sideLength / 2 + options.lineWidth / 2; // offset from the edge to the first square's center
 
     // the width of i ten frames plus the space between ten frames
-    const nextTenFrameXOffset = NUMBER_OF_X_SQUARES * options.sideLength + DISTANCE_BETWEEN_TEN_FRAMES + options.lineWidth / 2;
+    const nextTenFrameYOffset = NUMBER_OF_Y_SQUARES * options.sideLength + DISTANCE_BETWEEN_TEN_FRAMES + options.lineWidth / 2;
 
     for ( let i = 0; i < options.numberOfTenFrames; i++ ) {
-      const xOffset = i * nextTenFrameXOffset; // shift over for each additional ten frame
+      const yOffset = i * nextTenFrameYOffset; // shift over for each additional ten frame
 
       // iterate through all squares in a ten frame and record the center of each square
       for ( let j = 0; j < NUMBER_OF_Y_SQUARES; j++ ) {
         const y = j * options.sideLength + squareCenterOffset;
         for ( let k = 0; k < NUMBER_OF_X_SQUARES; k++ ) {
           const x = k * options.sideLength + squareCenterOffset;
-          spots.push( new Vector2( x + xOffset, y ) );
+          spots.push( new Vector2( x, y + yOffset ) );
         }
       }
     }
```

</details>

**Comment by amanda-phet** [comment]
It's pretty common for ten frames to be stacked horizontally or vertically when going up to 20, so there isn't a pedagogical reason for doing this. We chose the horizontal layout because it looks more aesthetically pleasing, and I'm not bothered by the different layouts because they are supposed to be different representations of the same numbers. 

So, I'm not sure which direction to go here, but I guess I prefer the horizontal look because they fill the accordion box better.
![image](https://user-images.githubusercontent.com/7852916/216658784-2e56090e-fd89-48ea-a08b-ffc6a6cd8c0d.png)

@catherinecarter and I can run this by our pedagogy experts when we see them later today, to see if they think it's an issue to compare 10x2 and 5x4.

**Comment by amanda-phet** [comment]
Update: 

Ian Whitacre said either representation is fine, but he likes the horizontal one better. He also mentioned that he isn't bothered to see them horizontal, and in fact conservation of cardinality is an important goal of this simulation. He also thinks it is a lot to look at when stacked vertically. 

So, I'd like to go ahead and revert this change and keep the ten frames laid out horizontally.

**Comment by marlitas** [comment]
@amanda-phet looks like this change was not permanently committed, so nothing to revert! Closing :-)
