### ISSUE TITLE
Conduct a performance profile

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-play#21]
6/17/21 Ian emailed us the following: 
>Number Play is not working on the iPads that I have. It opens and seems fine initially, but then the page reloads. I get the error message, “A problem occurred with this webpage so it was reloaded.” 

>This is Safari on an iPad version 10.3.3 

>Correction: It’s working on *some* of the iPads that I have :)

It might be a good idea to get a sense of the performance of the sim to figure out how to tackle this issue.

**Comment by chrisklus** [comment]
Startup performance appears to be as expected - each of the ScrenViews are taking comparable or less time to initialize than the Sim object. (I looked at other sims for comparison - each of EFAC's two SceenViews take longer to construct than the Sim object, and a few others look similar to Number Play). 

After everything is loaded, the performance of the sitting sim or while a paper one is being dragged around seems normal, even with 6x slowdown.

All recorded with 6x CPU throttling in Chrome.
<img width="640" alt="Screen Shot 2021-06-18 at 5 18 53 PM" src="https://user-images.githubusercontent.com/5618316/122623645-2917ed00-d05a-11eb-832f-635ec15f9f87.png">

Sitting sim after startup
<img width="640" alt="Screen Shot 2021-06-18 at 5 18 53 PM" src="https://user-images.githubusercontent.com/5618316/122624531-d0e2ea00-d05d-11eb-9e9a-2a41fb1322d4.png">

Dragging a paper one around after startup
<img width="640" alt="Screen Shot 2021-06-18 at 5 18 53 PM" src="https://user-images.githubusercontent.com/5618316/122624562-f5d75d00-d05d-11eb-9c87-6a6ce81905ed.png">


So initial findings aren't suggesting a performance problem on startup from what I can tell. It would be helpful to know more details about how the crash is triggered (does a user have to interact with something in the sim, etc). I will reach out to QA next week to see if they can reproduce this.

**Comment by chrisklus** [comment]
I am not sure of the state of this issue. It should definitely be verified by QA before prototype publication. @amanda-phet do you remember any more details that came from these findings with Ian?

**Comment by amanda-phet** [comment]
I think we found out that he was using an unsupported version of iOS, so I believe this issue can be closed.
