### ISSUE TITLE
Cards may move around when switching scenes when already in place

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-play#212]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
Found on master.
If you switch back and forth between the card scene and the locked scene, even though the cards should already be in place when switching to the locked scene they may rotate and move to new arrangements. This does not always happen, so I'm not sure of the exact cause.

**Visuals**
![lockshuffle](https://user-images.githubusercontent.com/41024075/227039084-ca0679e1-12b1-430f-b777-048dedf26d03.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Number Play‬
URL: https://bayes.colorado.edu/dev/phettest/number-play/number-play_en.html?ea&brand=phet
Version: 1.1.0-dev.9 (unbuilt)
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by chrisklus** [comment]
@zepumph and I fixed this in the above commits but we'd like to wait on testing it until changes in https://github.com/phetsims/number-suite-common/issues/12 have settled out more. Marking on-hold.

**Comment by chrisklus** [comment]
@Nancy-Salpepi and I noticed this occurring again when talking about (2) from https://github.com/phetsims/number-suite-common/issues/44

**Comment by zepumph** [comment]
Steps to reproduce a bug:
1. bring out a bunch with the number spinner thing
2. "link" the two play areas
3. combine two ones into a two while linked
4. split them up
5. Cycling between grouped and linked will result in a single object car animating to where the 2 value used to be over and over.

If this doesn't work, then likely you didn't pick something low enough in the z-order. I believe the "move to front" logic is part of the problem.

**Comment by chrisklus** [comment]
@zepumph and I believe this is fixed, and work over in https://github.com/phetsims/number-suite-common/issues/12 has been wrapped up, so we are ready to remove on:hold from this issue and resume testing. Feel free to close if it's fixed. Steps to reproduce this bug are written in https://github.com/phetsims/number-play/issues/212#issuecomment-1483096014. Assigning to @KatieWoe and @Nancy-Salpepi, thanks!

**Comment by Nancy-Salpepi** [comment]
Sorry! Question....
Should all the grouped cards move around in the following case:
1. Add all the ones to the play area
2. Combine some so there are three 2s on the screen
3. Press lock 
4. Press the cards scene
5. Separate 1 card containing two dogs, but don't move anything else
6. Press lock again --> instead of just the two dogs coming together on one card, I sometimes see 2 of the paired cards moving or even all 3 paired cards moving. Is that what is supposed to happen @chrisklus?

https://user-images.githubusercontent.com/87318828/227602193-f49ea93b-fceb-4c32-a40c-2ac44307b1b0.mp4

**Comment by zepumph** [comment]
Ahh, sorry @chrisklus and I lost this. Please re-assign next time for a faster response. I believe this is a bug. We should first loop through everything to see if there are matching positions, and then handle the moving case. Thanks @Nancy-Salpepi!



@chrisklus, perhaps something 2n<sup>2</sup> like this (untested):

<details>

```diff
Subject: [PATCH] push away logic will respect playAreaBounds and choose a new animation direction, https://github.com/phetsims/number-compare/issues/30
---
Index: js/common/model/CountingPlayArea.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/model/CountingPlayArea.ts b/js/common/model/CountingPlayArea.ts
--- a/js/common/model/CountingPlayArea.ts	(revision 3cc59301b277d173d1d511d28227d4ff3a707d0d)
+++ b/js/common/model/CountingPlayArea.ts	(date 1680103891671)
@@ -481,8 +481,8 @@
    *  the appropriate and exact county object state.
    */
   private linkToSerializedCountingObjects( targetCountingObjectSerializations: CountingObjectSerialization[],
-                                        linkStatusChangedEmitter: TEmitter<[ boolean ]>,
-                                        areObjectsLinkedToOnes: boolean ): void {
+                                           linkStatusChangedEmitter: TEmitter<[ boolean ]>,
+                                           areObjectsLinkedToOnes: boolean ): void {
 
     const objectsToOrganize = this.getCountingObjectsIncludedInSum();
 
@@ -502,13 +502,8 @@
 
     // Iterate through each input and try to mutate the current countingObjects list to support that target
     for ( let i = 0; i < inputSortedByValue.length; i++ ) {
-      assert && assert( countingObjectsSortedByValue.length > 0, 'still have serializations, but no CountingObjects left' );
-
       const targetSerialization = inputSortedByValue[ i ];
-
       const desiredValue = targetSerialization.numberValue;
-      let currentNumberValueCount = 0;
-      let targetHandled = false;
 
       // First see if there are any exact position/value matches, and keep those where they are.
       // Use a forEach because we may mutate the list inline.
@@ -519,12 +514,22 @@
         if ( currentCountingObject.numberValueProperty.value === desiredValue &&
              currentCountingObject.positionProperty.value.equals( targetSerialization.position ) ) {
           arrayRemove( countingObjectsSortedByValue, currentCountingObject );
+          arrayRemove( inputSortedByValue, currentCountingObject ); // TODO better mutation while iterating
           handledCountingObjects.push( currentCountingObject );
-          currentNumberValueCount += currentCountingObject.numberValueProperty.value;
           numberOfAnimationsFinishedProperty.value += 1;
-          targetHandled = true;
         }
       } );
+    }
+
+    for ( let i = 0; i < inputSortedByValue.length; i++ ) {
+      assert && assert( countingObjectsSortedByValue.length > 0, 'still have serializations, but no CountingObjects left' );
+
+      const targetSerialization = inputSortedByValue[ i ];
+
+      const desiredValue = targetSerialization.numberValue;
+      let currentNumberValueCount = 0;
+      let targetHandled = false;
+
 
       // Then, move or split the remaining countingObjects to match the serializations.
       while ( !targetHandled ) {

```
</details>

**Comment by zepumph** [comment]
We could also clean up an extra array. Ok @Nancy-Salpepi this should be handled better now. Sorry for our bad testing before.

**Comment by Nancy-Salpepi** [comment]
Both the original issue and the one in https://github.com/phetsims/number-play/issues/212#issuecomment-1483194273 look fixed to me! 🥳

Closing.
