### ISSUE TITLE
Should shape-visible time still change based on number of guesses?

### ISSUE THREAD

**Issue by zepumph** [phetsims/number-play#214]
Promoting TODO to issue:

https://github.com/phetsims/number-play/blob/9be45e4f7ed1ab73001c989dbe5708dbb58f074f/js/game/model/Subitizer.ts#L215-L220

@chrisklus asked for a new issue.

Basically, after 2 guesses, the time that the shape is shown increases (currently by .1 seconds per extra guess). @amanda-phet, is this still valuable to have? Or is a constant enough because we now have the `?subitizeTimeShown` query parameter?

@chrisklus please chime in if I didn't understand the problem correctly.

**Comment by zepumph** [comment]
Promoted its own issue from https://github.com/phetsims/number-suite-common/issues/29

**Comment by chrisklus** [comment]
@amanda-phet and I discussed and are okay to pull it out since we have a preferences control.

**Comment by chrisklus** [comment]
Committed above and tested on my machine. This felt like a safe change, closing.
