### ISSUE TITLE
Rename readAloud -> autoHear

### ISSUE THREAD

**Issue by zepumph** [phetsims/number-play#219]

**Comment by chrisklus** [comment]
Currently in the Preferences dialog we have "Hear Total" and "Hear Number Sentence". I think we should change these labels to something like "Automatically Hear Total" and "Automatically Hear Number Sentence", and update their descriptions accordingly. Or just update their descriptions in some way to be more explicit that having this off does not disable speech synthesis. Everyone who comes into the preferences audio tab with me to talk preferences thinks this control turns speech synthesis on and off, and that is indicative to me that we don't have the naming correct yet.

Once we do that, (or do nothing), we should update all the places in code to match. This setting (and original query parameter) is still call `readAloud` everywhere in the code base. If we made my recommended change from above, we could still have a unified name in code like `autoHear` or something similar. Right now we don't have a great unifying name to use in code, so I still usually reference this feature as readAloud, @pixelzoom has referenced it as "Hear...", etc. This makes it hard to talk about and code around and should be improved.

@amanda-phet any thoughts?

**Comment by chrisklus** [comment]
@amanda-phet and I met this morning and are good with the proposals above, i'll implement.

**Comment by chrisklus** [comment]
Remaining work:

- [x] update strings to include "Automatically"
- [ ] change query parameter to `autoHear`
- [ ] update remaining ReadAloud language in code to AutoHear

**Comment by chrisklus** [comment]
Rename complete and I tested in both sims. I think we are all set! Closing.
