### ISSUE TITLE
Master: objects are stacked on top of one another in counting games

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/number-play#220]
**Test device**
MacBook Air M1 chip

**Operating System**
13.2.1

**Browser**
Safari 

**Problem description**
Seen while confirming https://github.com/phetsims/number-play/issues/216: On the Game Screen in Level 1 and 2, the objects are always stacked on top of one another in the lower left corner.

**Visuals**

<img width="1258" alt="Screenshot 2023-04-06 at 8 08 20 AM" src="https://user-images.githubusercontent.com/87318828/230377027-343bbbf2-329b-4528-8e22-353f0e931db5.png">

**Comment by chrisklus** [comment]
Thanks @Nancy-Salpepi! Accidental (bad) regression. @zepumph I'm about to commit a fix.

**Comment by chrisklus** [comment]
Fixed in the above commit. This was affecting the first 3 screens. @Nancy-Salpepi can you please confirm on phettest? Feel free to close if looking good.

**Comment by chrisklus** [comment]
I believe @Nancy-Salpepi is out today so I did some testing of this feature on all affected screens on phettest. It is looking normal again. Closing.
