### ISSUE TITLE
Use number for testing words instead of full words

### ISSUE THREAD

**Issue by zepumph** [phetsims/number-play#221]
Over in https://github.com/phetsims/number-play/issues/218 @chrisklus and I realized a slight improvement would be to change "One two three" to "1 2 3" so that when using untranslated locales, the speech will still be in that language, "translated" by the speech voice knowing how to pronounce numbers.

This felt like a no brainer, small improvement to me, since we will eventually get quite a few translations. It is more of a stop gap for the case where "One two three" isn't translated yet.

Up to @chrisklus on how to proceed.

**Comment by chrisklus** [comment]
Committed above, thanks @zepumph for the brilliant idea and issue! This is sounding really nice. Closing.
