### ISSUE TITLE
Switching locales changes the voice, but not the language

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/number-play#224]
**Test device**
MacBook Air M1 chip

**Operating System**
13.2.1

**Browser**
Safari 

**Problem description**
For https://github.com/phetsims/qa/issues/929, when I toggle between two locales on the Ten/Twenty screen, the number is spoken in the new voice, but in the previous language. I have to change the number to hear the selected locale. 

Also seen with Win10 + chrome

**Steps to reproduce**
1. In preferences menu, turn on "Automatically Hear Total" and turn on/select a second locale 
2. On the Ten or Twenty screen, add 1 object to the play area
3. Toggle to the second locale --the voice and written word will change, but the spoken word isn't correct
4. Add another object to the play area--Voice and locale will be correct
5. Toggle back to English

**Visuals**

https://user-images.githubusercontent.com/87318828/230734241-4b916195-e2e9-4415-936e-499037269dd4.mov

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Number Play‬
URL: https://phet-dev.colorado.edu/html/number-play/1.1.0-rc.1/phet/number-play_all_phet.html
Version: 1.1.0-rc.1 2023-04-07 16:57:36 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15
Language: en-US
Window: 1293x705
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Nancy-Salpepi** [comment]
Something similar also happens when second locale is off:

1. Turn on "Automatically hear total"
2. Add objects to play area in either of the first 2 screens
3. Change locale in localization tab
4. press megaphone button

**Comment by chrisklus** [comment]
Thanks @Nancy-Salpepi! @samreid @zepumph and I pushed a fix in the above commits, and did some testing on our side, but are still a bit nervous about the change (think: problems that happened like in this issue https://github.com/phetsims/number-suite-common/issues/56). Can you please test on phettest and see how things are sounding? Thanks so much.

**Comment by Nancy-Salpepi** [comment]
@stemilymill and I both say this looks fixed in master!

**Comment by chrisklus** [comment]
Thanks @Nancy-Salpepi and @stemilymill! Patches applied in the above commits.

**Comment by Nancy-Salpepi** [comment]
I tried several locale combinations and didn't see any issues. 
Closing
