### ISSUE TITLE
Minus sign too small/low on card

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/number-play#225]
**Test device**
MacBook Air m1 chip

**Operating System**
13.2.1

**Browser**
safari/chrome

**Problem description**
For https://github.com/phetsims/qa/issues/929, on the lab screen, the minus sign isn't centered and the symbol is shorter than the others. 
<img width="326" alt="Screenshot 2023-04-10 at 11 58 22 AM" src="https://user-images.githubusercontent.com/87318828/230940861-e305a405-ac11-449c-b5a9-fee12280762f.png">

Looking at Equality Explorer: the minus sign is centered and its size matches the other operations.
<img width="158" alt="Screenshot 2023-04-09 at 9 02 30 AM" src="https://user-images.githubusercontent.com/87318828/230941042-23a23cfb-58b4-4bcc-a965-24ce2286508b.png">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Number Play‬
URL: https://phet-dev.colorado.edu/html/number-play/1.1.0-rc.1/phet/number-play_all_phet.html
Version: 1.1.0-rc.1 2023-04-07 16:57:36 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15
Language: en-US
Window: 1258x705
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by chrisklus** [comment]
Thanks @Nancy-Salpepi! @zepumph and I fixed this in the above commits. Can you please confirm on master for Number Play and Number Compare? Please pass to us for cherry picking if all looks good.

**Comment by Nancy-Salpepi** [comment]
That is one gorgeous minus sign 🙂. Looks good in both sims. Back to you.

**Comment by amanda-phet** [comment]
Thank you Nancy!! I have been meaning to make an issue for this for so long. Glad you caught it. And @chrisklus you used the right one :)

**Comment by chrisklus** [comment]
Patches applied in the above commits

**Comment by zepumph** [comment]
For QA: This is just a symbol change, ensure there is no layout weirdness or bugginess and feel free to close.

**Comment by Nancy-Salpepi** [comment]
Looks good!
