### ISSUE TITLE
On macOS10 + Safari multiple voices sound the same within a locale

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/number-play#229]
**Test device**
iMac

**Operating System**
10.15.7

**Browser**
safari 15.6.1

**Problem description**
For https://github.com/phetsims/qa/issues/929, when cycling through voices for English, 7 of them (both male and female) sound exactly the same. This also happens with Spanish Voices. 

This issue isn't present on this device with chrome or with macOS 13.2.1 + safari. 
My guess is this isn't worth the time to investigate, but I thought it was important to have the issue documented. 

**Visuals**

https://user-images.githubusercontent.com/87318828/231021823-9d10dcd8-8a2d-4da8-971d-3a5402f0e1d5.mov

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪かずあそび‬
URL: https://phet-dev.colorado.edu/html/number-play/1.1.0-rc.1/phet/number-play_all_phet.html
Version: 1.1.0-rc.1 2023-04-07 16:57:36 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Language: en-US
Window: 1508x773
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by chrisklus** [comment]
From 4/11 standup with @zepumph and @Nancy-Salpepi:

This seems out of our control to fix and is on an older platform. Closing as wontfix. Thanks @Nancy-Salpepi!
