### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-play#232]
This sim needs updated screenshots

**Comment by amanda-phet** [comment]
This is done. Over to @chrisklus to cherry-pick.

**Comment by chrisklus** [comment]
@zepumph and I confirmed that rc.3 has the latest main screenshot here: https://phet-dev.colorado.edu/html/number-play/1.1.0-rc.3/phet/number-play-600.png.

Full resolution and alt images are only included in production deploys. Closing.
