### ISSUE TITLE
Cherry pick new preferences icon

### ISSUE THREAD

**Issue by zepumph** [phetsims/number-play#233]
Commits are complete over in https://github.com/phetsims/joist/issues/919. We just need to cherry pick:

https://github.com/phetsims/joist/commit/2eda3a488258038df60b6e7d3e4c933b5e1ff0e1

The other one (https://github.com/phetsims/joist/commit/5fdf39bbffc034fd45696e6f6c6abb30db3000a8) is just updating how we scale things, and could come along if desired to keep things in sync.

**Comment by chrisklus** [comment]
Patches applied

**Comment by zepumph** [comment]
QA Please ensure that the new preferences icon is a gear (instead of the gear/person combo), and that it looks appropriate on all devices. Feel free to close if all is good.

**Comment by Nancy-Salpepi** [comment]
Looks good on mac + safari/chrome and iPad. Will leave open until other platforms are looked at.

**Comment by veillette** [comment]
For rc.2: it looks good on Windows 10 with Chrome.
