### ISSUE TITLE
Website link needs to link to the "_all" html file

### ISSUE THREAD

**Issue by zepumph** [phetsims/number-play#235]
Currently, we don't have good website support for this sim because we only link to single-locale html files. We really need the `all` file to get the multilingual benefits.

@chrisklus and I don't feel like this would block the publication of the sim, but likely would want to block any announcement of this simulation.

**Comment by zepumph** [comment]
Tagging @amanda-phet as I bet she has also been part of this conversation too.

**Comment by zepumph** [comment]
Maybe at the very least this is solved with the teacher tips. That doesn't seem too great though.

**Comment by amanda-phet** [comment]
I keep forgetting about this, but I would absolutely love to make this happen. Teacher Tips are not visible enough for this critical feature. Should we have a meeting that includes @mattpen and figure out how to publish this sim differently, or change the link that is provided on sim pages??

**Comment by zepumph** [comment]
Perhaps we are at a point where we can make the "main link" on sim pages be the `all` for every sim page, and still allow individual links in the translations table. @mattpen how hard would something like that be?

@amanda-phet, what stakeholders would need to be in a meeting to make a solution for number play happen?

**Comment by amanda-phet** [comment]
>Perhaps we are at a point where we can make the "main link" on sim pages be the all for every sim page, and still allow individual links in the translations table.

To be clear, the main link would be the "all" link, but would use a query parameter for the locale, right? So on the English page it would be https://phet.colorado.edu/sims/html/number-play/latest/number-play_all.html?locale=en. 

The benefit of using the "all" link in this way is that everyone can get to translations in the Localization tab! I could see a potential downside (but I am not knowledgeable about this) of that file be "bigger" than the localized file.

**Comment by chrisklus** [comment]
I discussed this with @kathy-phet tonight and for now we would just like to make a workaround for Number Play that we can get up on the website quickly. This would likely mean making somewhat of a hack in website-meteor/simulationBanner.js.

We would like to get to a point where we can use the `all` link for all sims, but that is an epic-level project and to support Number Play grants, we need to get something up sooner. Not all sims support dynamic layout or have a Localization tab yet, and making a structural change like this would likely involve changing a step between the sim being built and the metadata it provides the sim page. We also need to think about how to support this in apps.

**Comment by chrisklus** [comment]
On second thought after a quick message with @mattpen (who was thinking this would not be that hard of a change)... maybe this would be just as easy to change generally for all sim pages, only for the main play button link? And the sims that don't have a Localization tab yet would load the same as they are now with the locale-specific build, just via the `all` file and query parameter instead. And then the sims that do have it would all be available instead of just Number Play/Compare. Could be a nice step 1 for going in this direction at a more platform wide level. Something to think about, let's discus tomorrow!

**Comment by mattpen** [comment]
I changed the play link to _all, this will be available on the next deploy.

**Comment by mattpen** [comment]
@amanda-phet @chrisklus - this change has been deployed to production. Is there anything else to do here?

**Comment by amanda-phet** [comment]
I can confirm that it's working! I checked the sim page, translation table, and filter page, and all are behaving as discussed. I'll go ahead and close this.
