### ISSUE TITLE
"screen" specific screenshots needed

### ISSUE THREAD

**Issue by zepumph** [phetsims/number-play#236]
From https://github.com/phetsims/website/issues/1322, and implicated by @veillette running into this in https://github.com/phetsims/calculus-grapher/issues/335 as well. It isn't clear at all what is needed for this. @amanda-phet, can you please state what screenshot is needed and where it needs to go. I also posted for clarification over in the general issue.

**Comment by zepumph** [comment]
After discussing with @arouinfar and @amanda-phet. This isn't blocking. @amanda-phet please close this once you have added these to master.

**Comment by amanda-phet** [comment]
This is done. Closing.
