### ISSUE TITLE
Update color profile

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-play#24]
Ten screen background color: #d7ffe3
Number and Ten Frame background color: #9fedac

Twenty screen background color: #fff2dc
Number and Ten Frame background color: #f9d2ac

**Comment by chrisklus** [comment]
Updated above. @amanda-phet would you like to review on phettest? I like the new darker green on the ten screen, but it seems a little fluorescent in the numeral accordion box on the twenty screen. What do you think?

This sim was created before ColorProfile.js was created by default with new sims, so it doesn't have a Color Editor. I was going to add one, but ColorProfiles are being refactored as we speak over in https://github.com/phetsims/scenery-phet/issues/515, so I decided to wait to convert to the new pattern after consulting @samreid. 

@amanda-phet if you would like to try out any alternative colors in place then I'm happy to add the existing ColorProfile pattern so there is a Color Editor, and then can refactor it in the near future.

**Comment by amanda-phet** [comment]
@chrisklus and I reviewed and decided to also update the ones and objects panels to be #fcdcff and #ccefff, respectively.

**Comment by chrisklus** [comment]
Okay all set @amanda-phet if you think we're ready to close.

**Comment by amanda-phet** [comment]
I think it looks good for now. We might want to tone down the light orange and light green, but let's return to that after other things are in place.
