### ISSUE TITLE
Changes to Compare screen

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-play#25]
- [x] Change the background panels to be #d7ffe3 and #fff2dc
- [x] Make the counting block representation (and number line triangle) color-coded, using #96e2a8 and #f7d19f respectively
- [x] Add scene selection style radio buttons
- [x] Fix the number line proportions in the radio button
- [x] Add string below comparison statement that toggles on and off depending on the comparison checkbox
- [x] Make the accordion boxes a little less tall so the numerals can use more of the vertical space in the accordion box
- [x] Add organize buttons for each of the objects accordion boxes - moved to https://github.com/phetsims/number-play/issues/26
- [x] Make the counting blocks a tiny big smaller so that I can see more white space between them

![image](https://user-images.githubusercontent.com/7852916/125863649-7940a764-640f-4e70-8c6e-d6cb73b18409.png)

**Comment by chrisklus** [comment]
Ok ready for review on phettest!

**Comment by amanda-phet** [comment]
Everything looks great!
