### ISSUE TITLE
Add spinner buttons next to buckets

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-play#30]
We'd like something like this
![image](https://user-images.githubusercontent.com/7852916/126228622-db17d7e9-75f8-4613-a618-cb0483a2360f.png)

It seems like there is an issue with accordion box and being able to put content in the margin below the expandCollapseButton.

**Comment by amanda-phet** [comment]
I'd like to follow up on this issue with Ian and see what he is noticing in student interviews before we decide which UI component would help us solve this usability concern.

**Comment by chrisklus** [comment]
I know this is lower priority but yesterday i was playing around with a design that would allow us to use both spinner buttons and at a reasonable size (they are just a tiny bit smaller than the buttons in the twenty screen numeral box). I made a quick one-off with them in place for your meeting with Ian so yall can at least try out the functionality.

https://phet-dev.colorado.edu/html/number-play/1.0.0-dev.25/phet/number-play_en_phet.html

**Comment by amanda-phet** [comment]
We like having the buttons. There are concerns about the buttons being on a 2D plane and the bucket on a 3D plane. They also have a lot of contrast against the bucket, making them more appealing than dragging the object. 

Questions we'd like answered in interviews:
- Might want to consider switching the order to see what feels natural (consider a/b testing) 
- How do the buttons interact with touch? 

We probably need to revisit this topic because we aren't sure where to put the buttons. 

Ideas:
- should we make the bucket taller so the buttons have more padding around them? (we are liking this)
- we could try making the bucket narrower, providing more space to the side for the arrow buttons (we don't like this idea as much) 
- Camouflage the buttons a bit by picking a blue from the bucket gradient (we are liking this), but we need the disabled button to look different

<img width="109" alt="image" src="https://user-images.githubusercontent.com/7852916/132910776-9c863554-5e14-4389-96d6-614bc9c21500.png">

**Comment by amanda-phet** [comment]
@chrisklus needs to investigate the disabled button appearance in common code.

**Comment by amanda-phet** [comment]
@amanda-phet will mock up a "flat" front bucket with no back and no gradient to review.

**Comment by chrisklus** [comment]
>Also making the buttons circular on the buckets needs to happen.

I met with @pixelzoom today and we discussed how the current structure of sun buttons doesn't allow for this kind of change without duplicating the implementation of ArrowButton. @pixelzoom also recommended we reconsider the design of having the buttons on the bucket, as it doesn't look great, and it is much more intuitive for them to be vertically aligned (which reminded me of the design meeting conversation when it took us a while to decide which side increase and decrease should be on when horizontally aligned). I agreed with both of these thoughts.

Then I talked with @amanda-phet and we brainstormed what else might work - we did try putting the spinner buttons back in a vertical orientation to the right of the bucket, and it looked okay with a taller bucket, however they clashed with the scene selection buttons. Then, @amanda-phet had the brilliant idea of getting rid of the bucket and putting the objects and spinner buttons on a flat panel! I really like this idea, as the bucket has been bugging me for a while anyway (both its appearance in the context of this sim and the way the objects jump in and out of it). This also creates a more natural space for the spinner buttons.

Here are a couple mockups @amanda-phet sent me to try:

![image](https://user-images.githubusercontent.com/5618316/133566260-0404d415-1656-4eda-8349-c5bf2e375353.png)

![image](https://user-images.githubusercontent.com/5618316/133566725-453e7408-fe27-4729-b254-ae6eeb37cce2.png)

I gave this a first pass in the commit above - it ended up being a large structural change as I found some stale things from before the paper ones were driving the model of objects. I'm liking this direction a lot and am excited to keep going with it.

**Comment by pixelzoom** [comment]
Love it. Some might argue that it's not as fun as dragging things out of a bucket. But it's definitely more accessible.  I'd also argue that it's more usable universally - while dragging things out of a bucket may seem fun at first, it gets old really fast. My 2 cents...

**Comment by amanda-phet** [comment]
@kathy-phet mentioned she wanted to put this in front of kids and see how they use it. I will put it in front of my kindergartener as an informal test, and added this issue to my list of interview things to look out for when we conduct formal interviews.
