### ISSUE TITLE
Add dual language support

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-play#31]
We've broken this down into sub-tasks:
- [x] Add toggle when a second language is specified 
![image](https://user-images.githubusercontent.com/7852916/126229254-a5474a0c-985f-49df-9d27-7b57f1d3bb84.png)

- [x] Create query parameter (something like `secondLanguage` 
- [x] We will also need a way to test the query parameter before translation is available (typically available after sim publication). So Chris mentioned that we might need to get strings in rosetta so that in testing, a sim on bayes can access those strings to test the query parameter.
- [x] Work with @jbphet on the build process to figure out how to access translated strings when running a sim. This might require use of the sim built with all locales, we're not sure. 
- [x] Refactor the equality statement string so that the numbers are included (e.g. {{x}} is less than {{y}})

**Comment by amanda-phet** [comment]
@chrisklus and I were talking about this today, and I'm wondering if we could pull in translated strings for numbers with an API or something, since the word for 0-20 should be pretty easy to find out without relying on translators. And it would reduce the complexity of building the sim with translations. 

One open question would be how to handle the compare statement on the compare screen- we might not be able to translate that without translators, so we could leave it in the primary locale, or scrap this new ideas.

**Comment by amanda-phet** [comment]
I am going to also investigate looking for an easy way to access translations for 0-20. If there is a file somewhere and we could run a script, or some other way to get this information into the sim without manual translations.

**Comment by chrisklus** [comment]
@jbphet and I met this afternoon and were able to figure out a way for this to work with the `_all` version of the sim. I added initial support in the above commits. Labeling for discussion during design meeting tomorrow.

**Comment by amanda-phet** [comment]
Did we discuss this last week? I don't recall, and the label is still here. I am assigned and not sure if I still need to be. It seems like the query parameter is working well, and as long as translations come in, more locales will be available for the second language, so I don't think there's anything left for me to do here.

**Comment by amanda-phet** [comment]
I also updated the checklist. Most items are complete, and the ones relating to a preferences dialog are not priority for the prototype release.

**Comment by chrisklus** [comment]
I think all work for this issue not related to the preferences dialog is complete, so I'm going to close. I moved the remaining items over to #155.
