### ISSUE TITLE
Use speech synthesis to read simple text from some screens

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-play#32]
- [x] Factor out speech synthesis from self-voicing (@jessegreenberg )
- [x] Add a speech button that, when clicked, reads out the number on the Ten and Twenty screens
- [x] Add a speech button that, when clicked, reads out the comparison statement text on the Compare screen
- [x] Hide this speech button in the android app since speech synthesis doesn't work there

**Comment by jessegreenberg** [comment]
In the above commit, I added a `supportsSpeechSynthesis` flag which will enable voicingManager separately from `supportsVoicing` so it can be used without the surrounding voicing features. I think we are ready to try and use this in the sim.

**Comment by chrisklus** [comment]
Thanks @jessegreenberg for giving me a tour of how to use speech synthesis! This went really smoothly. Ready for review.

**Comment by amanda-phet** [comment]
This is working well on Safari and Chrome!

**Comment by chrisklus** [comment]
Nice! Working for me on Firefox too. If speech synthesis is not supported (or if it's turned off via the query parameter `supportsSpeechSynthesis=false`), the button is not added. Ready to close if you are.
