### ISSUE TITLE
Dragged object doesn't stay on top after allowing grouping

### ISSUE THREAD

**Issue by chrisklus** [phetsims/number-play#40]
@kathy-phet noticed that there was a case where, when the puppies were not linked or grouped, when one was dropped so that it overlapped another, it would go underneath the puppy that it should have been on top of.

To reproduce this, I found that the puppies in the play area needed to be grouped together and then split back apart before this could occur, see below:

![Kapture 2021-08-17 at 10 41 25](https://user-images.githubusercontent.com/5618316/129775323-5d9d038b-bf65-47b3-8908-8f69060149ba.gif)

I found code that was ordering stacks based on their number value if they were overlapping at all, but since we changed the "combining" nature in https://github.com/phetsims/number-play/issues/36 to just combine if the paper numbers are overlapping, this code was no longer needed since all objects that could be overlapping have a value of 1. I think the reason they were overlapping with the wrong z-order in some cases was just because nodes were given preference based on their position in the array for objects of the same value (1) instead of considering which one was just being dragged, too. Removing that code seems to have fixed the problem.

**Comment by chrisklus** [comment]
Committed above - @amanda-phet would you like to review?

**Comment by amanda-phet** [comment]
Looks fixed to me! I had noticed that before too. Thanks for fixing.
