### ISSUE TITLE
Ten-Frames do not reset in Lab Screen

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/number-play#41]
**Test device**
MacBook Air (m1 chip)

**Operating System**
11.4

**Browser**
Chrome 

**Problem description**
https://github.com/phetsims/qa/issues/696

In the lab screen, when reset button is selected, the 10-frames fail to reset. 

**Steps to reproduce**
1. Select the lab screen
2. Place 1 or more 10-frames into the play area. 
3. Place other objects/numbers into the play area.
4. Select the reset button--everything resets except the frames. 

**Visuals**

https://drive.google.com/file/d/1z9FnyswCh61_cRxz2rWc5CGEAl5bkcLk/view?usp=sharing

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Number Play‬
URL: https://phet-dev.colorado.edu/html/number-play/1.0.0-dev.22/phet/number-play_en_phet.html
Version: 1.0.0-dev.22 2021-08-06 03:14:48 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
Language: en-US
Window: 1452x659
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

**Comment by amanda-phet** [comment]
I forgot to say not to test this screen. Still a number of issues here, so I'll update https://github.com/phetsims/qa/issues/696
