### ISSUE TITLE
 When reset button is selected the object type is not reset

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/number-play#42]
**Test device**
Macbook Air (m1 chip)

**Operating System**
11.4

**Browser**
chrome

**Problem description**
https://github.com/phetsims/qa/issues/696

In the Ten and Twenty screens, when the reset button is selected, everything returns to its original state except that the object selected does not return to the dogs. This is not seen in the compare screen. 

**Steps to reproduce**
Here is an example to illustrate everything resets but the object type:

1. Select either the Ten or Twenty Screen. 
2. Open both accordion boxes at the top of the screen
3. Select the pairing button (2 dogs together icon)
4. Select the orange/turtle/apple and add some to the screen. 
5. Hit reset. 

**Visuals**
https://drive.google.com/file/d/17KAJywEokMNsjrxz1eXCRhB9pKqoPktp/view?usp=sharing

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Number Play‬
URL: https://phet-dev.colorado.edu/html/number-play/1.0.0-dev.22/phet/number-play_en_phet.html
Version: 1.0.0-dev.22 2021-08-06 03:14:48 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
Language: en-US
Window: 1452x659
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

**Comment by chrisklus** [comment]
Thanks @Nancy-Salpepi! Fixed in the commit above, closing.
