### ISSUE TITLE
Memory isn't maintained when switching between unpaired and paired screens

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/number-play#44]
**Test device**
MacBook Air (m1 chip)

**Operating System**
11.4

**Browser**
Safari

**Problem description**
https://github.com/phetsims/qa/issues/696

@amanda-phet and I observed this on a zoom call yesterday:

In either the Ten or Twenty screens, when switching between locked and paired modes, the memory of the objects is maintained. However, when moving between unpaired and paired, the objects that were paired are no longer on a card. They are still together but there is no card behind them. 

**Steps to reproduce**
1. Choose either the 10 or 20 screen
2. Select the locked mode 
3. Pair some objects or numbers
4. Switch to the paired mode (2 dogs together icon) and pair a couple of the objects together
5. Switch back and forth between those two modes (locked and paired) and you will see that the screens are preserved.
6. Switch to unpaired mode and then to paired mode. Anything you had paired will no longer be on a card.

**Visuals**
https://drive.google.com/file/d/1dxoPCOHiiGeoisb1pAci_oCay6yVx4K5/view?usp=sharing

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Number Play‬
URL: https://phet-dev.colorado.edu/html/number-play/1.0.0-dev.22/phet/number-play_en_phet.html?screens=1,2,3
Version: 1.0.0-dev.22 2021-08-06 03:14:48 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
Language: en-US
Window: 1440x659
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

**Comment by chrisklus** [comment]
Thanks @Nancy-Salpepi! The behavior described in this issue is now behaving as desired. When you switch from ungrouped mode back to grouped, the cards are brought back to the dogs. They are no longer grouped like they might have been when previously in grouped in mode, but that is intentional based on discussion from 1/20 design meeting. Closing.
