### ISSUE TITLE
When grabbing object in unpaired mode, it is being treated as though it is being removed from group

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/number-play#45]
**Test device**
Mac11 (m1 chip)

**Operating System**
11.4

**Browser**
safari

**Problem description**
https://github.com/phetsims/qa/issues/696

In either the 10 or 20 screen, after switching from paired mode to unpaired mode, when I place my mouse pointer over a previously paired object to move it, it treats it as though it is being removed from a group. My mouse pointer is no longer directly over the object. Whereas, when I move an object that was not previously paired, the mouse pointer stays over that object. 

**Steps to reproduce**
1. Choice either the 10 or 20 screen
2. Choose the paired mode (2 dogs together).
3. Group some objects together and keep a couple of them separate
4. Switch to unpaired mode. Grab an object from the front of the previously grouped objects. It treats it as though it is being removed from a group.

**Visuals**
https://drive.google.com/file/d/1L6WG4bdtaJ2N82xEgjQp0ErtzU5Yx34J/view?usp=sharing

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Number Play‬
URL: https://phet-dev.colorado.edu/html/number-play/1.0.0-dev.22/phet/number-play_en_phet.html?screens=1,2,3
Version: 1.0.0-dev.22 2021-08-06 03:14:48 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
Language: en-US
Window: 1440x659
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

**Comment by chrisklus** [comment]
Thanks @Nancy-Salpepi! This was fixed recently with work being done over in https://github.com/phetsims/number-play/issues/117. The newly unpaired objects are now no longer part of a group.
