### ISSUE TITLE
Make a spanish prototype

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-play#46]
Our partner would like a version of the sim in Spanish, so we'd like to build a version of this right away. 

1. We need @DianaTavares to provide some translated strings
2. Add the toggle switch for dual languages, but keep it disabled for now

Would be great to have this soon, right after https://github.com/phetsims/counting-common/issues/1

**Comment by chrisklus** [comment]
I met with @liam-mulhall today to discuss the options for using rosetta to for a non-published sim - it sounds like we don't currently have the tooling for this in place, so I will provide english strings to @DianaTavares and then can manually add an es file to babel in the format that rosetta would output. These would then be included in the next build for a dev version.

**Comment by chrisklus** [comment]
In the above commits I added the Spanish translations from @DianaTavares. I made a file with the translations in the same format that babel outputs. I also met with @jbphet yesterday to ask where I should keep this file, and he said it seemed reasonable to commit it straight to master as long as I included the history parts too, which just added @DianaTavares's id as the translator, gave an approximate epoch time of when I added them, and included the first value of the strings.

Notifying @kathy-phet that Number Play can be built in Spanish off of master at any time now.

**Comment by chrisklus** [comment]
Thanks to the guidance of @jessegreenberg, we were able to add support for translated voices. Right now, if no voice for the desired locale is found, it will revert to english and print a message to the console that says the voice was not found. This seems to be working nicely for Spanish.

I'm going to close this issue for now, as I believe all the requirements for this prototype have been met. We can continue general support for translations/a second locale over in https://github.com/phetsims/number-play/issues/31
