### ISSUE TITLE
Switch word and ten-frame 

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-play#49]
- [x] Since the locale toggle is in the "Word" accordion box, and that toggle also controls the language that is being spoken with the speech synthesis button, I think it would make sense for the accordion box to be closer to that button. 

- [x] Likewise, on the Compare screen, we'll need to add a locale toggle up near the speech synthesis button.

**Comment by chrisklus** [comment]
In the above commits, I swapped the positions of the word accordion box and ten frame accordion box. I don't dislike it, but it definitely doesn't feel as natural as the original layout. Maybe I'm just too used to how it was. 

Another possibility I thought of was to keep them how they were, and then move the speaker button to the left side of the word accordion box. To then make it not feel like that button is floating over there on its own, we could also put the pink align button on the left side of the pink box, top aligned. Then there would be controls on each side of the screen, so it would be mostly balanced. One down side of this could be that the speaker would no longer be in the same place on all three screens, and that feels pretty nice right now (and with the change above, the language toggle is also in a similar place on all three screens). Maybe something to discuss at the next design meeting.

I also factored out the language control code to its own file and then added it to the compare screen. To see its two possible positions, test with `supportsSpeechSynthesis=true` (default) and `supportsSpeechSynthesis=false`.

Ready for review on phettest @amanda-phet!

**Comment by amanda-phet** [comment]
Discussed this and the idea to have buttons in different locations, and I'd like to mock up a few of the button ideas to see how it looks.

**Comment by amanda-phet** [comment]
I mocked up the button options and prefer option (2) where the buttons are more rearranged (and Word is back on the left side). Option (1) looks a bit lop-sided to me now that there are a lot of buttons on one side and a lot of empty space on the other side.  

(1) All buttons are lined up on the right
![image](https://user-images.githubusercontent.com/7852916/134956878-005ca898-be26-453c-80bf-6d8dbbddf52b.png)


(2) Word is back on the left, Ten Frame on the right, and buttons are moved to be next to their respective accordion boxes
![image](https://user-images.githubusercontent.com/7852916/134956182-089dd414-acce-4af0-9af2-2e1c26a2fe57.png)


I would like to  move forward with (2) for now, and we can always move buttons later if we don't like it in practice.
