### ISSUE TITLE
Single object cannot be removed from groups larger than 11

### ISSUE THREAD

**Issue by chrisklus** [phetsims/number-play#51]
If you try to remove an object from a group of, say size 14 (on the twenty screen), 4 are removed as a group instead of one

**Comment by chrisklus** [comment]
Sounds good, let's check in on this issue at design meeting today.

**Comment by amanda-phet** [comment]
This is a question for Ian and other content experts. @amanda-phet will email Ian and ask his opinion, and see if he wants to run it by the teachers he is working with.
