### ISSUE TITLE
New grouping paradigm for objects

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/number-play#70]
When the user switches to a "grouping" mode, all single objects will get a card background and maintain their full size: 
![image](https://user-images.githubusercontent.com/7852916/139729149-0f7b2c91-e579-400c-8ce2-c3b2d4c65533.png)

As soon as someone layers 2 or more objects on top of each other, they shrink down and fill a ten-frame-ish layout.
![image](https://user-images.githubusercontent.com/7852916/139729440-52886754-941e-4009-a055-b0f71d91e4cf.png)

Ten objects will be arranged as a full ten-frame on a wider card (to match the paper 10):
![image](https://user-images.githubusercontent.com/7852916/139729271-868736d0-9d8d-4bee-93b8-ef470531420b.png)

10+n will have layered cards similar to paper numbers:
![image](https://user-images.githubusercontent.com/7852916/139729316-bf00fe63-02d9-4572-a051-25af87e79bde.png)

And twenty objects will fill the entire wide card: 
![image](https://user-images.githubusercontent.com/7852916/139729355-c525411a-1ccd-4bcf-a024-ea68b28c437c.png)

**Comment by chrisklus** [comment]
The initial pass of this work was completed. The remaining work to make the cards stack like the numbers and the small objects to return to big objects will be completed in #117.
