### ISSUE TITLE
Game Screen: Memory test

### ISSUE THREAD

**Issue by Luisav1** [phetsims/number-play#78]
From my self code review in #75 

| Test | Memory Usage (MB) |
| --- | --- |
| Immediately after load | 18.5 |
| After 1 min of fuzz | 29.8 |
| After 2 min of fuzz | 35.2 |
| After 3 min of fuzz | 41.3 |
| After 4 min of fuzz | 47.1 |
| After 5 min of fuzz | 47.0 |
| After 6 min of fuzz | 50.9 |
| After 7 min of fuzz | 53.6 |
| After 8 min of fuzz | 61.4 |
| After 9 min of fuzz | 63.7 |
| After 10 min of fuzz | 70.1 |

**Comment by pixelzoom** [comment]
I see in #84 you said:
> NOTE: There is a memory leak, which we suspect is related to the paper numbers. These are used in the game, but have not been refactored yet, so they should not be addressed in the Game review.

Sorry I missed that. But at least I confirmed it :)

**Comment by pixelzoom** [comment]
Further down in #84, I see:
> - [ ] Does a heap comparison using Chrome Developer Tools indicate a memory leak? (Describing this process is beyond the scope of this document.) Test on a version built using `grunt --minify.mangle=false`. Compare to testing results done by the responsible developer. Results can be found in #78.
> 
> NOTE: There is a memory leak, which we suspect is related to the paper numbers. These are used in the game, but have not been refactored yet, so they should not be addressed in the Game review.

Sorry I missed that, I was working on the earlier checklist item. But at least I confirmed it :)

**Comment by marlitas** [comment]
Did another memory test after work done in https://github.com/phetsims/number-play/issues/127
The results indicate there is no memory leak:
<img width="187" alt="Screenshot 2023-01-11 at 10 59 38 AM" src="https://user-images.githubusercontent.com/42476338/211882937-8bdcdfd9-74e9-431e-9a8a-fa069aaea442.png">

Passing on to @chrisklus for review, and feel free to close if all looks good.

**Comment by chrisklus** [comment]
Looks great, thanks! Closing.
