### ISSUE TITLE
Convert PlayObjectType to a supported enumeration pattern

### ISSUE THREAD

**Issue by Luisav1** [phetsims/number-play#80]
From #75 
>Are there any `TODO` or `FIXME` or `REVIEW` comments in the code?  They should be addressed or promoted to GitHub issues.

**Comment by pixelzoom** [comment]
I inspected PlayObjectType and it is an Enumeration.  It looks great, a nice example of using the `instanceType` option in an EnumerationValue class hierarchy.  

@chrisklus I think this can be closed.

**Comment by chrisklus** [comment]
Agreed, thanks. Closing.
