### ISSUE TITLE
Refactor the OnesPlayAreaNode

### ISSUE THREAD

**Issue by Luisav1** [phetsims/number-play#82]
From #75 
>Are there any `TODO` or `FIXME` or `REVIEW` comments in the code?  They should be addressed or promoted to GitHub issues.

The parts of CountingGameLevelNode.js, and other screens that are used for the play area need to be refactored once the play area is updated. Once the bounds handling for the OnesPlayArea and the paper numbers are improved, we don't need to add a y margin to them anymore.

**Comment by chrisklus** [comment]
This work was completed in https://github.com/phetsims/number-play/issues/118, closing.

**Comment by chrisklus** [comment]
Last TODO improved above, closing.
