### ISSUE TITLE
Unused images and string.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-play#85]
Related to #84...

> - [ ]  Does the sim build without warnings or errors?

There are images and a string that are flagged as unused.  I realize that only one of these is related to the Game screen (game_screen_placeholder_png.js), but perhaps things are at a point where some of these can be cleaned up.

```
>> Unused images module: number-play/images/compare_screen_placeholder_png.js
>> Unused images module: number-play/images/game_screen_placeholder_png.js
>> Unused images module: number-play/images/lab_screen_icon_png.js
>> Unused images module: number-play/images/lab_screen_placeholder_png.js
>> Unused images module: number-play/images/speaker_png.js
>> Unused string: key=screen.lab, value=Lab
```

**Comment by Luisav1** [comment]
@chrisklus and I finished this off together. Closing.
