### ISSUE TITLE
Image import identifier should match image file name.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-play#86]
Related to #84.

The dev team recently agreed (in https://github.com/phetsims/chipper/issues/1166) to make the `import` identifer match the file name (minus its suffix). And there will (soon?) be a lint rule that enforces this for image files.  That convention is not being followed for image imports in this sim.

For example, in NumberPlayGameScreen.js:

```ts
import gameScreenIconImage from '../../images/game_screen_icon_png.js';
```

`gameScreenIconImage` does not match `game_screen_icon_png`.

Two alternatives:

```ts
// rename the image file
import gameScreenIcon_png from '../../images/gameScreenIcon_png.js';

// rename the import identifier
import game_screen_icon_png from '../../images/game_screen_icon_png.js';
```

**Comment by chrisklus** [comment]
Completed in https://github.com/phetsims/chipper/issues/1177, closing.
