### ISSUE TITLE
Unclear whether listeners need to be de-registered

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-play#87]
For #84 (Game screen: code review)

> - [ ] Are there leaks due to registering observers or listeners? The following guidelines should be followed unless documentation (in-line or in implementation-notes.md) describes why following them is not necessary. 
> ...

I inspected a random selection of `link`, `lazyLink`, `addListener`, etc.  There are no in-line comments indicating whether `unlink`, `removeListener`, etc. is required.   And there is no section in implementation-notes.md describing the approach to memory management.  

If all/most such listeners can remain registered for the duration of the sim, it needs to be indicated somewhere.  I like to do that in the **Memory Management** section of implemention-notes.md, and identify any exceptions.  For example, from fourier-making-waves:

> **Memory Management**
> * **Dynamic allocation**: Most objects in this sim are allocated at startup, and exist for the lifetime of the
  simulation. The exceptions to that are: `Vector2` and [FourierComponent](https://github.com/phetsims/fourier-making-waves/blob/master/js/wavepacket/model/FourierComponent.js)
>
> * **Listeners**: Unless otherwise noted in the code, all uses of `link`, `addListener`, etc. do NOT need a corresponding
  `unlink`, `removeListener`, etc.

**Comment by marlitas** [comment]
Work for this was done in parallel in https://github.com/phetsims/number-play/issues/88. 

@chrisklus assigning to you for your review.

**Comment by chrisklus** [comment]
@marlitas and I co-reviewed and everything looks great, thanks! Closing.
