### ISSUE TITLE
Cannot verify whether `dispose` is handled properly.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-play#88]
For #84 

> - [ ] For each common-code component (sun, scenery-phet, vegas, …) that opaquely registers observers or listeners, is
there a call to that component’s `dispose` function, or is it obvious why it isn't necessary, or is there documentation
about why `dispose` isn't called?  An example of why no call to `dispose` is needed is if the component is used in
a `ScreenView` that would never be removed from the scene graph.
...
> - [ ] Do all types that require a `dispose` function have one? This should expose a public `dispose` function that calls `this.disposeMyType()`, where `disposeMyType` is a private function declared in the constructor.  `MyType` should exactly match the filename.

I can't tell what this sim's policy is for `dispose` -- What classes should implement `dispose`? When sohould `disposed` be called?   Similar to #87, this is something that should be described in implementation-notes.md. Identify what classes are dynamic (and therefore need `dispose`) and which exist for the lifetime of the sim.  I've also gotten in the habit of implementing a failing `dispose` method for subclasses that exist for the lifetime of the sim, and are not intended to be disposed.  Here's an example of how I documented this in fourier-making-waves:

> **Memory Management**
> * **Dynamic allocation**: Most objects in this sim are allocated at startup, and exist for the lifetime of the
  simulation. The exceptions to that are: `Vector2` and [FourierComponent](https://github.com/phetsims/fourier-making-waves/blob/master/js/wavepacket/model/FourierComponent.js).
...
> * **dispose:** All classes have a `dispose` method. Sim-specific classes whose instances exist for the lifetime of the
  sim are not intended to be disposed, and their `dispose` implementation looks like this:
> 
> ```js
> /**
>  * @public
>  * @override
>  */
> dispose() {
>   assert && assert( false, 'dispose is not supported, exists for the lifetime of the sim' );
> } 
> ```

**Comment by marlitas** [comment]
I added `dispose` methods as recommended by @pixelzoom above as well as code comments, and documentation in implementation-notes.md (number-suite-common) to clarify memory management throughout Number Suite sims. This documentation was added in accordance to my understanding of memory management after several days of exploration.

@chrisklus, please take a look when you get the chance, and let me know if there are incorrect assumptions that I made while doing this.

**Comment by chrisklus** [comment]
@marlitas and I co-reviewed and code and documentation and all looks great, thanks! Closing.
