### ISSUE TITLE
Most PNG files have no asset file.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-play#90]
For #84 

> - [ ] Is there a file in assets/ for every resource file in sound/ and images/? Note that there is _not necessarily_ a 1:1 correspondence between asset and resource files; for example, several related images may be in the same .ai file. Check license.json for possible documentation of why some reesources might not have a corresponding asset file.

This is not specific to the Game screen, but the Game screen does use image files.

This sim has a ton of PNG file. And assets/paper-numbers_number-play.ai is the only asset file that exists.  Looking at that file, it most certainly did not serve as the source file for all PNG files.  So it looks like there are many asset files that are missing.

I see this way too often in code reviews. Designers should get in the habit of always provide the asset file used to create PNG files. And developers should insist on getting the asset file if it's not provided.

**Comment by Luisav1** [comment]
@amanda-phet Could you provide the corresponding asset files we've used so far?

**Comment by amanda-phet** [comment]
I will take care of this when we have the final artwork! Most of the assets being used right now are temporary, but I am aware of the following things that might need assets: 

- [ ] objects used in play area (currently dog, apple, turtle, ball) 
- [ ] level selection icons 
- [ ] screen icons

When they are finalized I will upload assets, and provide attribution as not all will be created by me.

**Comment by amanda-phet** [comment]
All images should have assets now.
