### ISSUE TITLE
`showCorrectAnswer` query parameter is not used.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-play#91]
In NumberPlayQueryParameter.js, presumably related to the Game screen:

```js
  // always show the correct answer
  // For internal use only, not public facing.
  showCorrectAnswer: { type: 'flag' },
```

I can find no occurrences of `showCorrectAnswer` in the source code, so should it be deleted?

And for future reference, you should use `showAnswer`, which is defined in initialize-globals.js, because it can only be enabled via browser magic described in https://github.com/phetsims/special-ops/blob/master/doc/phetTeamMember.md, and therefore cannot be abused by a student.

**Comment by Luisav1** [comment]
For #84.

We are still using showCorrectAnswer in the source code, but will change it to showAnswer instead and remove showCorrectAnswer from NumberPlayQueryParameters.

**Comment by Luisav1** [comment]
Fixed in the commit above. Back to @chrisklus to review and close if everything is good.

**Comment by chrisklus** [comment]
Commit looks good, thanks. I also renamed `NumberPlayGameAnswerButtons.showCorrectAnswer` to `NumberPlayGameAnswerButtons.showAnswer` to be closer aligned with the general QP name. Closing
