### ISSUE TITLE
Non-standard design and implementation of `gameLevels` query parameter.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-play#92]
For #84 

In NumberPlayQueryParameters.js:

```js
  // the levels to show in the 'Game' screen
  gameLevels: {
    public: true,
    type: 'array',
    elementSchema: {
      type: 'string',
      isValidValue: element => GAME_LEVELS_DEFAULT_VALUES.includes( element )
    },
    defaultValue: GAME_LEVELS_DEFAULT_VALUES,

    // if provided, at least one level is required and repeated levels are not allowed
    isValidValue: array => ( array.length > 0 ) && ( array.length === _.uniq( array ).length )
  }
```

That implementation fails to keep levels sorted, which was requested by the design team when this general feature specified.  Unfortunately this query parameter can't be provided by the schema in initialize-globals.js, because every sim has a different number of game levels. (Perhaps we could provide common code that generates this schema?)

Here's the standard implementation, from FourierMakingWavesQueryParameters.js:

```js
  // The levels to show in the Wave Game screen.
  // The level numbers must be unique, valid, and in ascending order.
  // See https://github.com/phetsims/fourier-making-waves/issues/145
  gameLevels: {
    public: true,
    type: 'array',
    elementSchema: {
      type: 'number',
      isValidValue: Number.isInteger
    },
    defaultValue: null,
    isValidValue: array => {
      return ( array === null ) || (
        array.length > 0 &&
        // unique level numbers
        array.length === _.uniq( array ).length &&
        // valid level numbers
        _.every( array, element => element >= 1 && element <= FMWConstants.NUMBER_OF_GAME_LEVELS ) &&
        // sorted by ascending level number
        _.every( array, ( value, index, array ) => ( index === 0 || array[ index - 1 ] <= value ) )
      );
    }
  },
```

**Comment by pixelzoom** [comment]
> (Perhaps we could provide common code that generates this schema?)

Tracking in https://github.com/phetsims/query-string-machine/issues/47.

**Comment by chrisklus** [comment]
@pixelzoom what you identified from FMW fails and reverts to default values if the levels are out of order. I thought it would be a better user experience to allow whatever levels the user specifies, in any order, to loosen the restraints on their end. And then the sim orders them afterwards so the levels can't be displayed out of order:

```js
  /**
   * Returns the level number for each level code that matches the provided level character by extracting the level
   * numbers from the level codes. It also sorts them to ensure level x is displayed before level x+1 in case the level
   * codes were provided out of order.
   *
   * @param levelCodes - the array of two-character codes that represent game levels
   * @param levelCharacter - the character that indicates which level codes should be kept and turned into numbers
   */
  private static getLevelNumbers( levelCodes: string[], levelCharacter: string ): number[] {
    const levelsCodesToInclude = levelCodes.filter( levelCode => levelCode.includes( levelCharacter ) );
    const levelNumbers = levelsCodesToInclude.map( levelName => parseInt( levelName.replace( levelCharacter, '' ) ) ); // eslint-disable-line
    return _.sortBy( levelNumbers );
  }
```

But I agree it would be nice if this schema was generalized.

**Comment by pixelzoom** [comment]
Oh dear, I see  that there's something else going on here with `gameLevels`.  

In NumberPlayQueryParameters.js:

```js
// constants
const GAME_LEVELS_DEFAULT_VALUES = [
  `${NumberPlayConstants.A}1`, // a1
  `${NumberPlayConstants.A}2`, // a2
  `${NumberPlayConstants.B}1`, // b1
  `${NumberPlayConstants.B}2`  // b2
];
```

In NumberGameModel.js:

```js
    // get the level numbers specified by the gameLevels query parameter
    const gameALevelNumbers = NumberPlayGameModel.getLevelNumbers( NumberPlayQueryParameters.gameLevels,
      NumberPlayConstants.A );
    const gameBLevelNumbers = NumberPlayGameModel.getLevelNumbers( NumberPlayQueryParameters.gameLevels,
      NumberPlayConstants.B );
```

This naming/numbering scheme is contrary what was decided in other discussions about `gameLevel`.  I recall that we were going to always number levels, and that a number didn't have to correspond to difficulty.  It looks like an entire different design has been used in this sim.  And if the goal is for all sims to have a consistent `gameLevels` query parameter, this does not work.  So adding @amanda-phet to the assignments.

**Comment by pixelzoom** [comment]
> what you identified from FMW fails and reverts to default values if the levels are out of order.

That's because you've used an entirely different design and implementation for `gameLevels`.

> I thought it would be a better user experience to allow whatever levels the user specifies, in any order, to loosen the restraints on their end. 

This is not what was decided for the `gameLevels` query parameter in general, which (as I understood it) was supposed to operate consistently across all sims.

**Comment by chrisklus** [comment]
A decision was made in a design meeting for this sim to try expanding the API of `gameLevels` to allow for game screens containing multiple games. We thought it didn't make sense (in code or for the user) to only have numbers when dealing with two different games. But I see the issue if we are trying to use the exact same API for all games. Perhaps we can define two general APIs for `gameLevels` and a sim can select one to use. But the purpose of adding `a` and `b` (instead of something more sim specific) was to reuse this pattern (and eventually generalize it) for other multi-game-type game screens.

>That is not what was decided for the `gameLevels` query parameter in general, which (as I understood it) was supposed to operate consistently across all sims. 

Gotcha, that makes sense to me.

**Comment by pixelzoom** [comment]
I should also point out that the association of 'a' and 'b' to 'Counting' and 'Suitize' respectively is not documented in NumberPlayQueryParameters.js, NumberPlayConstants.js, or any place that I could identify.    I had to read through the NumberPlayGameModel constructor to tease out that 'a' is 'Counting' and 'b' is 'Suitize'.   So I'm wondering how the reader of NumberPlayQueryParameters.js is supposed to figure out what something like `?gameLevels=b1,a1` means.

**Comment by pixelzoom** [comment]
Of all the issues for #84 (code review) this is the one that concerns me the most.  I don't think it's a good idea to publish a sin with a public `gameLevels` query parameter whose format and behavior is inconsistent with other PhET sims.

History: 

The `gameLevels` query parameter was first discussed in https://github.com/phetsims/vegas/issues/86.

The design of the `gameLevels` query parameter was solidified, and it was first implemented in https://github.com/phetsims/equality-explorer/issues/165.  I don't see our design discussions captured in the issue, but I recall a meeting with @amanda-phet and @kathy-phet, with a specific goal of standardizing this query parameter (which is why the issue was originally in vegas).  Since @amanda-phet was invovled in that design, I'm surprised that `gameLevels` is so radically different in Number Play. 

The schema for `gameLevels` was copied and added to fourier-making-waves in https://github.com/phetsims/fourier-making-waves/issues/145.

**Comment by amanda-phet** [comment]
>This naming/numbering scheme is contrary what was decided in other discussions about gameLevel. I recall that we were going to always number levels, and that a number didn't have to correspond to difficulty. It looks like an entire different design has been used in this sim. And if the goal is for all sims to have a consistent gameLevels query parameter, this does not work. So adding @amanda-phet to the assignments.

As @chrisklus said, the Number Play game has two "games", each with two levels. We didn't think a numeric pattern made sense for identifying the games/levels to display. I see now that it is a very custom query parameter, but in the discussion we thought it was a pattern that would work for future sims with multiple games and levels on one screen. 

@pixelzoom I'm curious what you would recommend in this case. Would you just number each option 1,2,3,4 instead of a1, a2, b1, b2? When we discussed the user experience, it makes it seem like these games are increasing in difficult as you get to levels 3 and 4, but in fact we have two games with 2 levels each. Another thought we had was something like `game1Level` and `game2Level`, but decided it would be nicer to use the same name for the query parameter as in other sims. Now I am wondering if using the same name with different input types wasn't a good choice, since it differs so much from the other implementations.

**Comment by kathy-phet** [comment]
Just noting that 2 query parameters does not let us do all the combinations we want, unless designed to work a different way than the one query parameter.

**Comment by pixelzoom** [comment]
> @pixelzoom I'm curious what you would recommend in this case.

I'm not really recommending anything -- I'm just pointing out that we had a very general design discussion about `gameLevels`, with the goal that it should be a general query parameter (which was why it was in vegas) with consistent behavior. That consistent behavior is embodied in common code (see https://github.com/phetsims/vegas/issues/100) and is used by all sims that support the `gameLevels` query parameter - expect Number Play. If that's OK with you, then leave it as is, but expect to have to deal with the inconsistency in documentation. (The documentation is currently very incomplete.)

If it were me... I'd have 4 levels in Number Play, numbered 1,2,3,4, identified as such in the `gameLevels` query parameter documentation, and in model.md.   Because as we've descided previous, levels do not necessarly indicate degree of difficulty, they simply indicate different challenges, with different behaviors/conditions.

**Comment by amanda-phet** [comment]
12/16/21 meeting discussion: 
* reviewed history of the qp and issue at hand
* considered using ascending numerals no matter the game type (in this case 1,2,3,4, and in the case of Fractions, 1-20) 

Brainstormed ideas for renaming this variant of gameLevels, so it sounds similar, but has a different name so that it doesn't get confusing. This qp would have input type of string, and would have custom ranges for each sim that uses it.  
* `gameChoices`
* `gameType`

Would be nice to allow gameChoices=a and get all levels of that game type (for example in Fractions Intro game, 10 levels would be a lot to list out if someone wants all levels of the first game type). 

For a future sim, or for the fractions games, we might want to consider an option to allow gameChoices=a1-a10 or something that displays a range of levels for a game type. 

Decision: @chrisklus will move ahead with calling this `gameChoices`, but we'd like to hear @pixelzoom 's opinion on how we are choosing to structure it (input is sim-specific, and in this case inputs could be a1, a2, b1, b2, a, b).

**Comment by pixelzoom** [comment]
I would stick with `gameLevels`, I don't think this needs to be different or so complicated.

Document the values of `gameLevels` for this sim like this:

```
1: Counting, Level 1
2: Counting, Level 2
3: Subitize, Level 1
4: Subitize, Level 2
```

In NumberPlayGameLevels.js:

```js
    this.countingLevels = [ new CountingGameLevel( 1 ), new CountingGameLevel( 2 ) ];
    this.subitizeLevels = [ new SubitizeGameLevel( 1 ),  new SubitizeGameLevel( 2 ) );
    this.levels = [ ...this.countingLevels, ...this.subitizeLevels ];
```

Then hide level-selection buttons for the levels that are not included in `gameLevels`.

This will fix a BIG problem that you currently have, and which I did not notice/report. In the model, you're conditionally creating game levels based on the value of `gameLevels`.  When this sim gets instrumented for PhET-iO, that will cause it to fail, because excluding levels will change the PhET-iO API.  You must ALWAYS create all 4 levels, then expose only the ones specified by `gameLevels` to the user.   And I recommend handling that in the view (not the model) by hiding level-selection buttons based on `gameLevels`.  See equality-explore.LevelSelectionNode and fourier-making-waves.WaveGameLevelSelectionNode for examples.

**Comment by pixelzoom** [comment]
If you need getGameLevelsSchema.js to be flexible about the ordering of values (e.g. `gameLevels=3,1`), we can easily add an option for that.

**Comment by kathy-phet** [comment]
Chris - Sorry to miss you today. One take away from the discussion today was how gameLevels 1,2,3,4 implicitly implies a "getting harder" kind of notion. You can document the intention, but the implication is hard to disassociate. So given that we have other games (like Build a Fraction) that have different kinds of games that should not be compared as harder, and are likely to have additional sims that don't strickly adhere to leveling up, the consensus that came out of this discussion was that having two parameters was useful. We agreed that we shouldn't use one parameter for both cases. 

gameLevels for when it is one kind of game with clear levels 
gameChoices for when accommodating game screens that have different styles of games (denoted by letters) and levels of each (denoted by numbers)

WIth the documentation used to communicate about the query parameter and allowed options.

Your points about PhET-iO and eagerly creating the games all make sense to me, regardless of the query parameter name.

**Comment by pixelzoom** [comment]
> One take away from the discussion today was how gameLevels 1,2,3,4 implicitly implies a "getting harder" kind of notion. You can document the intention, but the implication is hard to disassociate. 

I understand.  But we did discuss this point explicitly when we originally designed the `gameLevels` parameter, and concluded that it wasn't a big deal in a query parameter.  After all, we have "level selection buttons" in the code, we refer to the buttons UI as "the level selection screen", etc. and we aren't planning to change that terminology.  

What you're seeing here is internal terminology leaking out to become public facing.  I would be concern about that leak if it was appearing in the UI, but it's not.  It's appearing in a configuration feature to be used by teachers, after they have read some documetation.  What I am concerned about is that the proposal to address the leak: is difficut to describe; complicates the query parameter, making it harder to use; makes it inconsistent; doesn't use common code; requires it's own complicted implementation, will be an ongoing cost to maintain;...  All of that same seems unnecessary when you could use the same `gameLevels` schema and simply explain to teachers (via a couple of lines of documentation) that "Levels" doesn't mean "difficultly" in this case.  

This is just my recommendation, and it's not my sim,

**Comment by pixelzoom** [comment]
Other reasons whey I feel`gameChoice` is not a good direction ...  

(1) You're proposing to change the definition of "game" and "level", and introduce something called "choice". This was at first confusing to me when doing the code review, and I did figure it out.  But I would argue that the impact/cost of that difference was much larger (and more expensive) that it the design team had stuck to the common-code use of "game" and "level", and stuck with the `gameLevels` query parameter. 

(2) Using different terminology will make it even more difficult for PhET to develop a common-code frame work for games.  PhET's vegas repository is currently just a collection of UI components that can be used to assemble a game screen; it does not provide any type of common game framework. Game screens have been historically expensive to implement (2x or more than non-game screens). And implementing a game screen currently involves copying some patterns and code from other sims, which results in duplicate code, makes bugs difficult to fix, etc.  So PhET does need such a framework, but that task has been deferred until we have more games, so we can identify more commonalities/patterns.  Deviations from standards (like what's proposed here) will make the possibily of accompishing that task less likely.

**Comment by pixelzoom** [comment]
@kathy-phet said:
> One take away from the discussion today was how gameLevels 1,2,3,4 implicitly implies a "getting harder" kind of notion. You can document the intention, but the implication is hard to disassociate.

From the broader gaming community, here's a definition of "game level" https://www.webopedia.com/definitions/game-level/:

> A game level is a section or part of a game. Most games are so large that they are broken up into levels, so only one portion of the game needs to load at one time. To complete a game level, a gamer usually needs to meet specific goals or perform a specific task to advance to the next level. In puzzle games, levels may be similar but more difficult as you progress through the game.

Note the use of "usually" and "may" in this definition; there can be exceptions.  While it may be the case that game levels usually get more difficult, it's not set in concrete.  And I would argue that that is another reason why we should stick with `gameLevels`, and simply add documentation to address your concern about "the implication".

**Comment by pixelzoom** [comment]
Here's `gameLevels` implementation if it's done like in other sims, full-supported by common code:

```
// Chooses the game levels that you want to appear in this sim.  
// Note that unlike some other PhET sims, higher level numbers are not necessarily more difficult.
// The values correspond to the games as follows:
// 1: Counting, Level 1
// 2: Counting, Level 2
// 3: Subitize, Level 1
// 4: Subitize, Level 2
gameLevels: getGameLevelsSchema( 4 ),
```

Here's `gameLevels` with the "choices" proposal:

````js
const GAME_LEVELS_DEFAULT_VALUES = [ 'a1', 'a2', 'b1', 'b2' ];
];

// Chooses the game levels that you want to appear in this sim.  
// The values correspond to the games as follows:
// a1: Counting, Level 1
// a2: Counting, Level 2
// b1: Subitize, Level 1
// b2: Subitize, Level 2
//
// Note that 'a' is 'Counting', and 'b' is Subitize.
  gameLevels: {
    public: true,
    type: 'array',
    elementSchema: {
      type: 'string',
      isValidValue: element => GAME_LEVELS_DEFAULT_VALUES.includes( element )
    },
    defaultValue: GAME_LEVELS_DEFAULT_VALUES,

    // if provided, at least one level is required and repeated levels are not allowed
    isValidValue: array => ( array.length > 0 ) && ( array.length === _.uniq( array ).length )
  }
```

Then you'll need to write a parser to decode 'a1', etc.  And there's no

**Comment by pixelzoom** [comment]
I like @ariel-phet's suggestion (at 12/21 design meeting) about being able to specify a range, like `gameLevel=1-4,9-12`.  But that's not supported by PhET's query parameter implementation, and adding it would be a significant piece of work.   So since a query parameter is something you usually set up once, I would (for now) put the burden back on the user to type (e.g.) `gameLevel=1,2,2,4,9,10,11,12`.

**Comment by amanda-phet** [comment]
We decided in the 12/21 design meeting to move ahead with `gameLevels` and *not* make a custom query parameter.

**Comment by Luisav1** [comment]
@chrisklus and I worked on this issue. We are unsure of how much to let the query parameter level numbers leak into the sim code since the model currently thinks of them as level 1 and level 2 for each game so we'll continue tomorrow.

<details/>

```diff
Index: js/common/NumberPlayQueryParameters.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/NumberPlayQueryParameters.js b/js/common/NumberPlayQueryParameters.js
--- a/js/common/NumberPlayQueryParameters.js	(revision 65d0632139e7c45af49c138ae6faff80c1a1b825)
+++ b/js/common/NumberPlayQueryParameters.js	(date 1640112821009)
@@ -7,17 +7,10 @@
  * @author Chris Klusendorf (PhET Interactive Simulations)
  */
 
+import getGameLevelsSchema from '../../../vegas/js/getGameLevelsSchema.js';
 import numberPlay from '../numberPlay.js';
 import NumberPlayConstants from './NumberPlayConstants.js';
 
-// constants
-const GAME_LEVELS_DEFAULT_VALUES = [
-  `${NumberPlayConstants.A}1`, // a1
-  `${NumberPlayConstants.A}2`, // a2
-  `${NumberPlayConstants.B}1`, // b1
-  `${NumberPlayConstants.B}2`  // b2
-];
-
 const NumberPlayQueryParameters = QueryStringMachine.getAll( {
 
   // time that the objects are shown when they “flash” in the ‘Subitize’ game, in seconds. If the user gets the answer
@@ -28,20 +21,14 @@
     defaultValue: NumberPlayConstants.SHAPE_VISIBLE_TIME
   },
 
-  // the levels to show in the 'Game' screen. 'a' levels correspond to the 'Counting' game, while 'b' levels
-  // correspond to the 'Subitize' game
-  gameLevels: {
-    public: true,
-    type: 'array',
-    elementSchema: {
-      type: 'string',
-      isValidValue: element => GAME_LEVELS_DEFAULT_VALUES.includes( element )
-    },
-    defaultValue: GAME_LEVELS_DEFAULT_VALUES,
-
-    // if provided, at least one level is required and repeated levels are not allowed
-    isValidValue: array => ( array.length > 0 ) && ( array.length === _.uniq( array ).length )
-  }
+  // Chooses the game levels that you want to appear on the 'Game' screen.
+  // Note that unlike some other PhET sims, higher level numbers are not necessarily more difficult.
+  // The values correspond to the games as follows:
+  // 1: Counting, Level 1
+  // 2: Counting, Level 2
+  // 3: Subitize, Level 1
+  // 4: Subitize, Level 2
+  gameLevels: getGameLevelsSchema( 4 )
 
 } );
 
Index: js/common/NumberPlayConstants.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/NumberPlayConstants.js b/js/common/NumberPlayConstants.js
--- a/js/common/NumberPlayConstants.js	(revision 65d0632139e7c45af49c138ae6faff80c1a1b825)
+++ b/js/common/NumberPlayConstants.js	(date 1640112295184)
@@ -112,10 +112,6 @@
 
   // game screen
 
-  // generic naming for the two types of games (used for specifying game types with query parameters)
-  A: 'a',
-  B: 'b',
-
   // subitizer game
   SHAPE_DELAY_TIME: 0.5, // amount of time to delay before showing the shape
   SHAPE_VISIBLE_TIME: 0.5, // amount of time the shape is shown, in seconds
Index: js/game/view/NumberPlayGameLevelSelectionNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/game/view/NumberPlayGameLevelSelectionNode.ts b/js/game/view/NumberPlayGameLevelSelectionNode.ts
--- a/js/game/view/NumberPlayGameLevelSelectionNode.ts	(revision 65d0632139e7c45af49c138ae6faff80c1a1b825)
+++ b/js/game/view/NumberPlayGameLevelSelectionNode.ts	(date 1640129492044)
@@ -75,28 +75,25 @@
     };
 
     // creates all level selection buttons for a level and returns only the levels specified by the gameLevels query parameter
-    const getLevelSelectionButtons = (
-      levels: NumberPlayGameLevel[],
-      gameType: string,
-      gameColorProperty: ProfileColorProperty
-    ): LevelSelectionButton[] => {
-      const levelSelectionButtons: LevelSelectionButton[] = [];
-      const levelNumbers = NumberPlayGameLevelSelectionNode.getLevelNumbers( NumberPlayQueryParameters.gameLevels, gameType );
-      levels.forEach( level => {
-        const levelSelectionButton = createLevelSelectionButton( level, gameColorProperty );
-        if ( levelNumbers.includes( level.levelNumber ) ) {
-          levelSelectionButtons.push( levelSelectionButton );
-        }
-      } );
-      return levelSelectionButtons;
-    };
+    const getLevelSelectionButtons = ( levels: NumberPlayGameLevel[], gameColorProperty: ProfileColorProperty ) =>
+      levels.map( level => createLevelSelectionButton( level, gameColorProperty ) );
 
     // create the level selection buttons for the each game
-    const countingGameLevelSelectionButtons = getLevelSelectionButtons( model.countingLevels, NumberPlayConstants.A,
+    const countingGameLevelSelectionButtons = getLevelSelectionButtons( model.countingLevels,
       NumberPlayColors.countingGameColorProperty );
-    const subitizeGameLevelSelectionButtons = getLevelSelectionButtons( model.subitizeLevels, NumberPlayConstants.B,
+    const subitizeGameLevelSelectionButtons = getLevelSelectionButtons( model.subitizeLevels,
       NumberPlayColors.subitizeGameColorProperty );
 
+    const levelSelectionButtons = [ ...countingGameLevelSelectionButtons, ...subitizeGameLevelSelectionButtons ];
+
+    // Hide buttons for levels that are not included in gameLevels query parameter.
+    // We must still create these buttons so that we don't change the PhET-iO API.
+    if ( NumberPlayQueryParameters.gameLevels ) {
+      levelSelectionButtons.forEach( button => {
+        button.visible = NumberPlayQueryParameters.gameLevels.includes( ??? );
+      } );
+    }
+
     // arrange and add the level selection buttons
     const levelSelectionButtonsBox = new VBox( {
       children: [
@@ -125,20 +122,6 @@
     } );
     this.addChild( resetAllButton );
   }
-
-  /**
-   * Returns the level number for each level code that matches the provided level character by extracting the level
-   * numbers from the level codes. It also sorts them to ensure level x is displayed before level x+1 in case the level
-   * codes were provided out of order.
-   *
-   * @param levelCodes - the array of two-character codes that represent game levels
-   * @param levelCharacter - the character that indicates which level codes should be kept and turned into numbers
-   */
-  private static getLevelNumbers( levelCodes: string[], levelCharacter: string ): number[] {
-    const levelsCodesToInclude = levelCodes.filter( levelCode => levelCode.includes( levelCharacter ) );
-    const levelNumbers = levelsCodesToInclude.map( levelName => parseInt( levelName.replace( levelCharacter, '' ) ) ); // eslint-disable-line
-    return _.sortBy( levelNumbers );
-  }
 }
 
 numberPlay.register( 'NumberPlayGameLevelSelectionNode', NumberPlayGameLevelSelectionNode );
```

**Comment by chrisklus** [comment]
The way we are controlling the visibility of the level buttons doesn't feel as clean as it worked out in Fourier, but what we committed above feels like a better solution than "mixing" the external facing level numbers in with the model. Closing.
