### ISSUE TITLE
Improve documentation for `subitizerTimeVisible` query parameter.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-play#93]
For #84 

In NumberPlayQueryParameters.js

```js
  // time the shape is shown in the subitize game
  subitizerTimeVisible: {
    public: true,
    type: 'number',
    defaultValue: NumberPlayConstants.SHAPE_VISIBLE_TIME
  },
```

This needs better documentation. What units are the time? What is "the shape"? (And why "the shape"? I see spheres, apples, etc. and certainly not singular.)

It's also not clear when this time is used.  From the code, it looks like it's only used conditionally:

```js
    // how long the shape is visible when shown, in seconds. This is a derived Property instead of a constant because
    // the time that the shape is shown is increased if the user gets the answer wrong multiple times.
    this.timeToShowShapeProperty = new DerivedProperty( [ numberOfAnswerButtonPressesProperty ],
      numberOfAnswerButtonPresses => {
        if ( numberOfAnswerButtonPresses > NumberPlayConstants.NUMBER_OF_SUBITIZER_GUESSES_AT_NORMAL_TIME ) {
          return this.timeToShowShapeProperty.value + NumberPlayConstants.SHAPE_VISIBLE_TIME_INCREASE_AMOUNT;
        }
        return NumberPlayQueryParameters.subitizerTimeVisible;
      } );
```

**Comment by pixelzoom** [comment]
Since this is `public: true`, it's especially important to improve the doc and make sure this is working as expected.

**Comment by Luisav1** [comment]
Fixed in the commit above. Back to @chrisklus to review and close if all is good.

**Comment by chrisklus** [comment]
Thanks @Luisav1 - I moved the units into the description since `NumberPlayConstants.SHAPE_VISIBLE_TIME` already has units where it's declared, and added some specificity with how it relates to a single challenge. Closing.
