### ISSUE TITLE
Drop the "Property" suffix on the `colorName` argument to `new ProfileColorProperty`.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-play#94]
For #84 

> - [ ] All sims should use a color file named `MyRepoColors.js` or, if using abbreviations, `MRColors.js`, and
  use `ProfileColorProperty` where appropriate, even if they have a single (default) profile (to support color editing 
  and PhET-iO Studio). The `ColorProfile` pattern was converted to `*Colors.js` files in https://github.com/phetsims/scenery-phet/issues/515. Please see [GasPropertiesColors.js](https://github.com/phetsims/gas-properties/blob/master/js/common/GasPropertiesColors.js) for a good example.

The first arument to `new ProfileColorProperty` is the `colorName`.  The convention is to drop the "Property" suffix, as shown in the GasPropertiesColors.js example referenced in the checklist item. 

In NumberPlayColors.js, the "Property" suffix is present, e.g. 'tenScreenBackgroundColorProperty' in:

```js
  tenScreenBackgroundColorProperty: new ProfileColorProperty( numberPlay, 'tenScreenBackgroundColorProperty', {
    default: LIGHT_GREEN_BACKGROUND
  } ),
```

Compare to GasPropertiesColors.js, e.g. 'screenBackgroundColor':

```js
  screenBackgroundColorProperty: new ProfileColorProperty( gasProperties, 'screenBackgroundColor', {
    default: 'black',
    projector: 'white'
  } ),
```

**Comment by Luisav1** [comment]
Fixed in the commit above, back to @chrisklus for review and to close if everything is fixed.

**Comment by chrisklus** [comment]
Looks great, thanks. Closing.
