### ISSUE TITLE
OnesCreatorPanel.js has incorrect JSDoc

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-play#95]
In OnesCreatorPanel.js, incorrect JSDoc, flagged by WebStorm:

```js
  /**
   * @param {MakeATenExploreScreenView} screenView
   * @param {NumberProperty} sumProperty
   * @param {Object} [options] - Passed to Node
   */
  constructor( playArea, screenView, options ) {
```

**Comment by chrisklus** [comment]
Thanks @pixelzoom. I had that WebStorm setting turned off for some reason, but found the setting that flagged the problem when turned on. Fixed and closing.
