### ISSUE TITLE
Incorrect uses of "property".

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-play#98]
For #84 

> - [ ]  Differentiate between `Property` and "property" in comments. They are different things. `Property` is a type in AXON; property is any value associated with a JavaScript object. Often "field" can be used in exchange for "property" which can help with clarity. Search for "property" to identify violations.

In NumberPlayGameAnswerButtons.js, "property" and "properties" are incorrect:

```
      // used to disable individual buttons but the true 'enabledProperty' for this button relies on other properties
      // too, see the derived property usage below
```

**Comment by Luisav1** [comment]
Fixed in the commit above. Back to @chrisklus for review to close if everything is fixed.

**Comment by chrisklus** [comment]
Commit looks good and I didn't see any other incorrect usages, closing.
