### ISSUE TITLE
Investigate replacing 'SubitizeGameLevel | CountingGameLevel' with NumberPlayGameLevel

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-play#99]
For #84 
> - [ ]  Is inheritance used where appropriate? Does the type hierarchy make sense?

In CountingGameLevel.js:

```ts
  public step( dt: number ): void {
  }
```

I wondered why this no-op `step` method is here.  I'm guessing that it's because in NumberPlayGameModel.js, you're expecting all levels to have a `step` method:

```ts
  public step( dt: number ): void {
    this.levels.forEach( level => level.step( dt ) );
  }
```

If that's the case, then `step` should be part of the NumberPlayGameLevel base class API, either as a default no-op implementation, or abstract.  Ditto for `reset`, which should be public in NumberPlayGameLevel.

Then I noticed in NumberPlayGameModel.js:

```ts
  public readonly levels: Array<SubitizeGameLevel | CountingGameLevel>;
  public readonly levelProperty: Property<SubitizeGameLevel | CountingGameLevel | null>
```

It seems to me that there are a lot of places where you're using `SubitizeGameLevel | CountingGameLevel` that could be `NumberPlayGameLevel`.   But you're missing some things that should be in the NumberPlayGameLevel API:

* `step`
* `reset` should be public
* ??

**Comment by Luisav1** [comment]
@chrisklus and I worked on this together. We weren't able to add the step function in the base class as an abstract without overriding it as a no-op in CountingGameLevel, so we just made it no-op in the base class and deleted it from CountingGameLevel. After that and making reset() public, we were able to use NumberPlayGameLevel as the parameter type everywhere. Closing.
